Repository BitcoinDesign/Guide, pull requests merged in 2020-12, with the labels that each got.

#69 Deleting various unused pages like bounties, history and blog
  _drafts/2020-07-02-draft.markdown
  _includes/disqus_comments.html
  _includes/header.html
  _layouts/home-original.html
  _layouts/post.html
  _posts/2020-07-02-welcome-to-jekyll.markdown
  blog.md
  bounties.md
  history.md
  home.md
  projects/first-research-project.md
  projects/second-research-project.md
Labels: dev

#70 Script for auto-resizing Figma embeds
  _sass/minima/_article.scss
  js/scripts.js
  style.md
Labels: dev

#67 Projects page light cleanup
  _sass/minima/_layout.scss
  _sass/minima/_projects-page.scss
  _sass/minima/initialize.scss
  about.md
  assets/images/contribute/bisq.png
  assets/images/contribute/bisq.svg
  assets/images/contribute/bitcoin-core.svg
  assets/images/contribute/bitcoin-design-guide.svg
  assets/images/contribute/btcpay.png
  assets/images/contribute/btcpay.svg
  assets/images/contribute/coinswap.png
  assets/images/contribute/electrum.png
  assets/images/contribute/electrum.svg
  assets/images/contribute/photon-lib.png
  assets/images/contribute/samourai-wallet.svg
  assets/images/contribute/samurai.png
  assets/images/contribute/wasabi-wallet.png
  assets/images/contribute/wasabi.png
  contribute.md
  projects.md
Labels: copy

#68 Update image and copy for the "Contribute" page
  _layouts/guide.html
  assets/images/contribute/contribute-mobile.jpg
  assets/images/contribute/contribute-mobile@2x.jpg
  assets/images/contribute/contribute-preview.jpg
  assets/images/contribute/contribute.jpg
  assets/images/contribute/contribute@2x.jpg
  contribute.md
Labels: copy, design

#76 Added the html-proofer plugin and fixed issues
  Gemfile
  Gemfile.lock
  RAKEFILE
  README.md
  _includes/home-banner.html
  _includes/secondary-nav.html
  _sass/minima/_article.scss
  _sass/minima/_layout.scss
  _sass/minima/_nav-list.scss
  _sass/minima/_site-footer.scss
  _sass/minima/_site-header.scss
  guide.md
  guide/getting-started/open-design.md
  guide/getting-started/usage-life-cycle.md
  guide/getting-started/why-design-for-bitcoin.md
  style.md
Labels: dev

#74 Moved content guidelines and style pages into resources folder
  assets/images/guide/resources/wallet-features.md
  assets/images/style/example-image-square.jpg
  assets/images/style/example-image-square@2x.jpg
  assets/images/style/example-image-wide-desktop.jpg
  assets/images/style/example-image-wide-desktop@2x.jpg
  assets/images/style/example-image-wide-mobile.jpg
  assets/images/style/example-image-wide-mobile@2x.jpg
  guide/resources/content-guidelines.md
  guide/resources/formatting.md
  guide/resources/resources.md
Labels: documentation

#77 Adds the site nav to the home page
  _includes/social.html
  _layouts/home.html
  about.md
  contribute.md
  index.md
  js/scripts.js
  js/search-page.js
  projects.md
  search-data.json
  search.html
Labels: dev

#79 fix: offset heading anchors to compensate for nav
  _sass/minima/_article.scss
Labels: dev

#85 Fixes header spacing trick to prevent blocking of other elements
  _sass/minima/_article.scss
  _sass/minima/_layout.scss
Labels: bug
