Repository BitcoinDesign/Guide, pull requests merged in 2021-05, with the labels that each got.

#269 Replaces the blockchain.com screens with Muun screens
  _compress_images_cache.yml
  assets/images/guide/getting-started/common-user-flows/blockchain-com-onboarding.jpg
  assets/images/guide/getting-started/common-user-flows/blockchain-com-onboarding@2x.jpg
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-1.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-10.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-10@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-1@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-2.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-2@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-3.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-3@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-4.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-4@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-5.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-5@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-6.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-6@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-7.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-7@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-8.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-8@2x.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-9.png
  assets/images/guide/getting-started/common-user-flows/muun-onboarding-9@2x.png
  guide/getting-started/common-user-flows.md
Labels: design

#277 Fixes sidebar scrolling when many sections are expanded
  _sass/minima/_layout.scss
  _sass/minima/_side-bar.scss
Labels: bug

#261 Revise vertical spacing between elements
  _layouts/home.html
  _sass/minima/_article.scss
  _sass/minima/_base.scss
  _sass/minima/_home-banner.scss
  _sass/minima/_home-page.scss
  _sass/minima/_layout.scss
  _sass/minima/_site-footer.scss
  _sass/minima/article/_dl.scss
  _sass/minima/article/_do.scss
  _sass/minima/article/_fact.scss
  _sass/minima/article/_footnotes.scss
  _sass/minima/article/_image-gallery.scss
  _sass/minima/article/_image-slide-gallery.scss
  _sass/minima/article/_tip.scss
  _sass/minima/initialize.scss
  guide/foundations/principles.md
  guide/onboarding/introduction.md
Labels: dev

#271 Add home page banner full-width background images option
  _compress_images_cache.yml
  _sass/minima/_home-banner.scss
  assets/images/home/banner/the-meta-future-mobile.jpg
  assets/images/home/banner/the-meta-future-mobile@2x.jpg
  assets/images/home/banner/the-meta-future.jpg
  assets/images/home/banner/the-meta-future@2x.jpg
  js/themes.js
Labels: design, dev

#225 Onboarding - Creating a new wallet page
  _compress_images_cache.yml
  _sass/minima/_base.scss
  assets/images/guide/onboarding/banner.svg
  assets/images/guide/onboarding/creating-a-new-wallet/onboarding-welcome-screen.png
  assets/images/guide/onboarding/creating-a-new-wallet/onboarding-welcome-screen@2x.png
  assets/images/guide/onboarding/creating-a-new-wallet/product-intro-1.png
  assets/images/guide/onboarding/creating-a-new-wallet/product-intro-1@2x.png
  assets/images/guide/onboarding/creating-a-new-wallet/product-intro-2.png
  assets/images/guide/onboarding/creating-a-new-wallet/product-intro-2@2x.png
  assets/images/guide/onboarding/creating-a-new-wallet/product-intro-3.png
  assets/images/guide/onboarding/creating-a-new-wallet/product-intro-3@2x.png
  assets/images/guide/onboarding/getting-to-know-your-users-mobile.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users-mobile@2x.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users/banner-mobile.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users/banner-mobile@2x.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users/banner.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users/banner@2x.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users/highest-motivator-battery.svg
  assets/images/guide/onboarding/getting-to-know-your-users/lowest-barrier-battery.svg
  assets/images/guide/onboarding/getting-to-know-your-users/lowest-motivator-battery.svg
  assets/images/guide/onboarding/getting-to-know-your-users/neutral-barrier-battery.svg
  assets/images/guide/onboarding/getting-to-know-your-users/neutral-motivator-battery.svg
  assets/images/guide/onboarding/getting-to-know-your-users/strongest-barrier-battery.svg
  assets/images/guide/payments/transactions/tx-preview.jpg
  guide/onboarding/creating-a-new-wallet.md
  guide/onboarding/getting-to-know-your-users.md
  guide/onboarding/introduction.md
Labels: copy

#284 Refreshed images for the send page
  _compress_images_cache.yml
  assets/images/guide/payments/send/first-confirmation-mobile.png
  assets/images/guide/payments/send/first-confirmation-mobile@2x.png
  assets/images/guide/payments/send/first-confirmation.png
  assets/images/guide/payments/send/first-confirmation.svg
  assets/images/guide/payments/send/first-confirmation@2x.png
  assets/images/guide/payments/send/get-recipient-address.png
  assets/images/guide/payments/send/get-recipient-address.svg
  assets/images/guide/payments/send/get-recipient-address@2x.png
  assets/images/guide/payments/send/input-address.png
  assets/images/guide/payments/send/input-address.svg
  assets/images/guide/payments/send/input-address@2x.png
  assets/images/guide/payments/send/input-amount.png
  assets/images/guide/payments/send/input-amount.svg
  assets/images/guide/payments/send/input-amount@2x.png
  assets/images/guide/payments/send/review-payment.png
  assets/images/guide/payments/send/review-payment.svg
  assets/images/guide/payments/send/review-payment@2x.png
  assets/images/guide/payments/send/select-fee-rate.png
  assets/images/guide/payments/send/select-fee-rate.svg
  assets/images/guide/payments/send/select-fee-rate@2x.png
  guide/payments/send.md
Labels: design

#293 Revision to "Submit a banner" page
  _compress_images_cache.yml
  assets/images/home/banner/figma-preview-mobile.png
  assets/images/home/banner/figma-preview-mobile@2x.png
  assets/images/home/banner/figma-preview.png
  assets/images/home/banner/figma-preview@2x.png
  assets/images/home/banner/template-overview-mobile.jpg
  assets/images/home/banner/template-overview-mobile@2x.jpg
  submit-header-design.md
Labels: copy

#301 Visual revision of the personal finance page
  _compress_images_cache.yml
  assets/images/guide/getting-started/personal-finance/coffee.jpg
  assets/images/guide/getting-started/personal-finance/coffee@2x.jpg
  assets/images/guide/getting-started/personal-finance/daily-spending-wallet-setup-mobile.jpg
  assets/images/guide/getting-started/personal-finance/daily-spending-wallet-setup-mobile@2x.jpg
  assets/images/guide/getting-started/personal-finance/daily-spending-wallet-setup.jpg
  assets/images/guide/getting-started/personal-finance/daily-spending-wallet-setup@2x.jpg
  assets/images/guide/getting-started/personal-finance/glacier-protocol-wallet-setup-mobile.jpg
  assets/images/guide/getting-started/personal-finance/glacier-protocol-wallet-setup-mobile@2x.jpg
  assets/images/guide/getting-started/personal-finance/glacier-protocol-wallet-setup.jpg
  assets/images/guide/getting-started/personal-finance/glacier-protocol-wallet-setup@2x.jpg
  assets/images/guide/getting-started/personal-finance/monthly-budget-wallet-setup-mobile.jpg
  assets/images/guide/getting-started/personal-finance/monthly-budget-wallet-setup-mobile@2x.jpg
  assets/images/guide/getting-started/personal-finance/monthly-budget-wallet-setup.jpg
  assets/images/guide/getting-started/personal-finance/monthly-budget-wallet-setup@2x.jpg
  assets/images/guide/getting-started/personal-finance/personal-finance-mobile.jpg
  assets/images/guide/getting-started/personal-finance/personal-finance-mobile@2x.jpg
  assets/images/guide/getting-started/personal-finance/personal-finance-preview.jpg
  assets/images/guide/getting-started/personal-finance/personal-finance.jpg
  assets/images/guide/getting-started/personal-finance/personal-finance@2x.jpg
  assets/images/guide/getting-started/personal-finance/savings-wallet-setup-mobile.jpg
  assets/images/guide/getting-started/personal-finance/savings-wallet-setup-mobile@2x.jpg
  assets/images/guide/getting-started/personal-finance/savings-wallet-setup.jpg
  assets/images/guide/getting-started/personal-finance/savings-wallet-setup@2x.jpg
  assets/images/guide/getting-started/personal-finance/stocks.jpg
  assets/images/guide/getting-started/personal-finance/stocks@2x.jpg
Labels: design

#298 Revised images in the Usage Life Cycle page
  _compress_images_cache.yml
  assets/images/guide/getting-started/usage-life-cycle/aware.jpg
  assets/images/guide/getting-started/usage-life-cycle/aware.png
  assets/images/guide/getting-started/usage-life-cycle/aware@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/aware@2x.png
  assets/images/guide/getting-started/usage-life-cycle/dropoff.jpg
  assets/images/guide/getting-started/usage-life-cycle/dropoff.png
  assets/images/guide/getting-started/usage-life-cycle/dropoff@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/dropoff@2x.png
  assets/images/guide/getting-started/usage-life-cycle/first-use.jpg
  assets/images/guide/getting-started/usage-life-cycle/first-use.png
  assets/images/guide/getting-started/usage-life-cycle/first-use@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/first-use@2x.png
  assets/images/guide/getting-started/usage-life-cycle/interested.jpg
  assets/images/guide/getting-started/usage-life-cycle/interested.png
  assets/images/guide/getting-started/usage-life-cycle/interested@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/interested@2x.png
  assets/images/guide/getting-started/usage-life-cycle/passionate-use.jpg
  assets/images/guide/getting-started/usage-life-cycle/passionate-use.png
  assets/images/guide/getting-started/usage-life-cycle/passionate-use@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/passionate-use@2x.png
  assets/images/guide/getting-started/usage-life-cycle/repeat-use.jpg
  assets/images/guide/getting-started/usage-life-cycle/repeat-use.png
  assets/images/guide/getting-started/usage-life-cycle/repeat-use@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/repeat-use@2x.png
  assets/images/guide/getting-started/usage-life-cycle/unaware.jpg
  assets/images/guide/getting-started/usage-life-cycle/unaware.png
  assets/images/guide/getting-started/usage-life-cycle/unaware@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/unaware@2x.png
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle-mobile.jpg
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle-mobile.png
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle-mobile@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle-mobile@2x.png
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle-preview.jpg
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle-preview.png
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle.jpg
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle.png
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle@2x.jpg
  assets/images/guide/getting-started/usage-life-cycle/usage-life-cycle@2x.png
  guide/getting-started/usage-life-cycle.md
Labels: design

#290 Update open-design.md
  guide/getting-started/open-design.md
Labels: copy

#283 Split private key management section into more pages
  guide/private-key-management/backups.md
  guide/private-key-management/cloud-backup.md
  guide/private-key-management/external-signing-device.md
  guide/private-key-management/manual-backup.md
  guide/private-key-management/multi-key.md
  guide/private-key-management/overview.md
  guide/private-key-management/shared-multi-key.md
  guide/private-key-management/single-user-schemes.md
  guide/private-key-management/threshold-signatures.md
Labels: copy

#309 Revised images in the Tech primer page
  assets/images/guide/getting-started/technology/address-and-private-key.jpg
  assets/images/guide/getting-started/technology/address-and-private-key@2x.jpg
  assets/images/guide/getting-started/technology/addresses.jpg
  assets/images/guide/getting-started/technology/addresses@2x.jpg
  assets/images/guide/getting-started/technology/balance.jpg
  assets/images/guide/getting-started/technology/balance@2x.jpg
  assets/images/guide/getting-started/technology/bitcoin-capitalization.jpg
  assets/images/guide/getting-started/technology/bitcoin-capitalization@2x.jpg
  assets/images/guide/getting-started/technology/block.jpg
  assets/images/guide/getting-started/technology/block@2x.jpg
  assets/images/guide/getting-started/technology/blockchain.jpg
  assets/images/guide/getting-started/technology/blockchain@2x.jpg
  assets/images/guide/getting-started/technology/derivation.jpg
  assets/images/guide/getting-started/technology/derivation@2x.jpg
  assets/images/guide/getting-started/technology/encryption.jpg
  assets/images/guide/getting-started/technology/encryption@2x.jpg
  assets/images/guide/getting-started/technology/hashing.jpg
  assets/images/guide/getting-started/technology/hashing@2x.jpg
  assets/images/guide/getting-started/technology/mempool.jpg
  assets/images/guide/getting-started/technology/mempool@2x.jpg
  assets/images/guide/getting-started/technology/mining-a-block.jpg
  assets/images/guide/getting-started/technology/mining-a-block@2x.jpg
  assets/images/guide/getting-started/technology/node.jpg
  assets/images/guide/getting-started/technology/node@2x.jpg
  assets/images/guide/getting-started/technology/public.jpg
  assets/images/guide/getting-started/technology/public@2x.jpg
  assets/images/guide/getting-started/technology/signature.jpg
  assets/images/guide/getting-started/technology/signature@2x.jpg
  assets/images/guide/getting-started/technology/transaction.jpg
  assets/images/guide/getting-started/technology/transaction@2x.jpg
  assets/images/guide/getting-started/technology/whitepaper.jpg
  assets/images/guide/getting-started/technology/whitepaper@2x.jpg
  guide/getting-started/technology-primer.md
Labels: design

#303 Revised images in the User Research page
  assets/images/guide/getting-started/user-research/adoption.jpg
  assets/images/guide/getting-started/user-research/adoption@2x.jpg
  assets/images/guide/getting-started/user-research/global-audience.jpg
  assets/images/guide/getting-started/user-research/global-audience@2x.jpg
  assets/images/guide/getting-started/user-research/private.jpg
  assets/images/guide/getting-started/user-research/private@2x.jpg
  assets/images/guide/getting-started/user-research/public-ledger.jpg
  assets/images/guide/getting-started/user-research/public-ledger@2x.jpg
  assets/images/guide/getting-started/user-research/user-research.jpg
  assets/images/guide/getting-started/user-research/user-research@2x.jpg
Labels: design

#306 Add gallery of screens to the multisig case study page
  _compress_images_cache.yml
  assets/images/guide/case-studies/multisig-wallet/backup-info.png
  assets/images/guide/case-studies/multisig-wallet/backup-info@2x.png
  assets/images/guide/case-studies/multisig-wallet/change-private-key scheme.png
  assets/images/guide/case-studies/multisig-wallet/change-private-key scheme@2x.png
  assets/images/guide/case-studies/multisig-wallet/continue-later.png
  assets/images/guide/case-studies/multisig-wallet/continue-later@2x.png
  assets/images/guide/case-studies/multisig-wallet/create-multi-key-wallet.png
  assets/images/guide/case-studies/multisig-wallet/create-multi-key-wallet@2x.png
  assets/images/guide/case-studies/multisig-wallet/create-recovery-key.png
  assets/images/guide/case-studies/multisig-wallet/create-recovery-key@2x.png
  assets/images/guide/case-studies/multisig-wallet/create-signing-key.png
  assets/images/guide/case-studies/multisig-wallet/create-signing-key@2x.png
  assets/images/guide/case-studies/multisig-wallet/creation-complete.png
  assets/images/guide/case-studies/multisig-wallet/creation-complete@2x.png
  assets/images/guide/case-studies/multisig-wallet/export-wallet.png
  assets/images/guide/case-studies/multisig-wallet/export-wallet@2x.png
  assets/images/guide/case-studies/multisig-wallet/external-device-setup.png
  assets/images/guide/case-studies/multisig-wallet/external-device-setup@2x.png
  assets/images/guide/case-studies/multisig-wallet/first.png
  assets/images/guide/case-studies/multisig-wallet/first@2x.png
  assets/images/guide/case-studies/multisig-wallet/home.png
  assets/images/guide/case-studies/multisig-wallet/home@2x.png
  assets/images/guide/case-studies/multisig-wallet/import-multi-key.png
  assets/images/guide/case-studies/multisig-wallet/import-multi-key@2x.png
  assets/images/guide/case-studies/multisig-wallet/import-wallet.png
  assets/images/guide/case-studies/multisig-wallet/import-wallet@2x.png
  assets/images/guide/case-studies/multisig-wallet/input-recovery-phrase.png
  assets/images/guide/case-studies/multisig-wallet/input-recovery-phrase@2x.png
  assets/images/guide/case-studies/multisig-wallet/more-information.png
  assets/images/guide/case-studies/multisig-wallet/more-information@2x.png
  assets/images/guide/case-studies/multisig-wallet/recover-wallet.png
  assets/images/guide/case-studies/multisig-wallet/recover-wallet@2x.png
  assets/images/guide/case-studies/multisig-wallet/recovery-key-setup.png
  assets/images/guide/case-studies/multisig-wallet/recovery-key-setup@2x.png
  assets/images/guide/case-studies/multisig-wallet/replace-key.png
  assets/images/guide/case-studies/multisig-wallet/replace-key@2x.png
  assets/images/guide/case-studies/multisig-wallet/second.png
  assets/images/guide/case-studies/multisig-wallet/second@2x.png
  assets/images/guide/case-studies/multisig-wallet/settings.png
  assets/images/guide/case-studies/multisig-wallet/settings@2x.png
  guide/case-studies/multisig-wallet.md
Labels: copy, design

#312 Fixes links that I broke in #283
  guide/case-studies/cloud-backup.md
  guide/case-studies/multisig-wallet.md
  guide/onboarding/creating-a-new-wallet.md
  guide/private-key-management/introduction.md
  guide/private-key-management/overview.md
  guide/private-key-management/shared-multi-key.md
Labels: copy

#240 Create receive page in payments section
  _compress_images_cache.yml
  assets/images/guide/payments/receive/address-info.png
  assets/images/guide/payments/receive/address-info@2x.png
  assets/images/guide/payments/receive/address-switch.png
  assets/images/guide/payments/receive/address-switch@2x.png
  assets/images/guide/payments/receive/enter-details-amount.png
  assets/images/guide/payments/receive/enter-details-amount@2x.png
  assets/images/guide/payments/receive/enter-details-compact.png
  assets/images/guide/payments/receive/enter-details-compact@2x.png
  assets/images/guide/payments/receive/enter-details-from.png
  assets/images/guide/payments/receive/enter-details-from@2x.png
  assets/images/guide/payments/receive/enter-details-purpose.png
  assets/images/guide/payments/receive/enter-details-purpose@2x.png
  assets/images/guide/payments/receive/receive-pending-details.png
  assets/images/guide/payments/receive/receive-pending-details@2x.png
  assets/images/guide/payments/receive/receive-with-pending.png
  assets/images/guide/payments/receive/receive-with-pending@2x.png
  assets/images/guide/payments/receive/share-sharesheet.png
  assets/images/guide/payments/receive/share-sharesheet@2x.png
  assets/images/guide/payments/receive/share.png
  assets/images/guide/payments/receive/share@2x.png
  assets/images/guide/payments/receive/simple-share-address-settings.png
  assets/images/guide/payments/receive/simple-share-address-settings@2x.png
  assets/images/guide/payments/receive/simple-share.png
  assets/images/guide/payments/receive/simple-share@2x.png
  assets/images/guide/payments/receive/transactions-no-label-context.png
  assets/images/guide/payments/receive/transactions-no-label-context@2x.png
  assets/images/guide/payments/receive/transactions-with-label-context.png
  assets/images/guide/payments/receive/transactions-with-label-context@2x.png
  guide/glossary.md
  guide/payments/introduction.md
  guide/payments/receive.md
  guide/payments/send.md
Labels: copy

#279 Add gallery of screens to the daily spending case study page
  _compress_images_cache.yml
  assets/images/guide/case-studies/cloud-backup/advanced-options.png
  assets/images/guide/case-studies/cloud-backup/advanced-options@2x.png
  assets/images/guide/case-studies/cloud-backup/backup-info.png
  assets/images/guide/case-studies/cloud-backup/backup-info@2x.png
  assets/images/guide/case-studies/cloud-backup/balance.png
  assets/images/guide/case-studies/cloud-backup/balance@2x.png
  assets/images/guide/case-studies/cloud-backup/case-cash-mobile.png
  assets/images/guide/case-studies/cloud-backup/case-cash-mobile@2x.png
  assets/images/guide/case-studies/cloud-backup/case-cash.png
  assets/images/guide/case-studies/cloud-backup/case-cash@2x.png
  assets/images/guide/case-studies/cloud-backup/change-private-key-scheme.png
  assets/images/guide/case-studies/cloud-backup/change-private-key-scheme@2x.png
  assets/images/guide/case-studies/cloud-backup/export-wallet.png
  assets/images/guide/case-studies/cloud-backup/export-wallet@2x.png
  assets/images/guide/case-studies/cloud-backup/first.png
  assets/images/guide/case-studies/cloud-backup/first@2x.png
  assets/images/guide/case-studies/cloud-backup/home.png
  assets/images/guide/case-studies/cloud-backup/home@2x.png
  assets/images/guide/case-studies/cloud-backup/import-wallet.png
  assets/images/guide/case-studies/cloud-backup/import-wallet@2x.png
  assets/images/guide/case-studies/cloud-backup/input-recovery-phrase.png
  assets/images/guide/case-studies/cloud-backup/input-recovery-phrase@2x.png
  assets/images/guide/case-studies/cloud-backup/more-information.png
  assets/images/guide/case-studies/cloud-backup/more-information@2x.png
  assets/images/guide/case-studies/cloud-backup/recovery-phrase.png
  assets/images/guide/case-studies/cloud-backup/recovery-phrase@2x.png
  assets/images/guide/case-studies/cloud-backup/second.png
  assets/images/guide/case-studies/cloud-backup/second@2x.png
  assets/images/guide/case-studies/cloud-backup/settings.png
  assets/images/guide/case-studies/cloud-backup/settings@2x.png
  guide/case-studies/cloud-backup.md
Labels: copy, design

#316 Backups - Add reference to Shamir secret sharing
  guide/private-key-management/backups.md
Labels: enhancement

#299 Link transactions page to sending bitcoin page
  guide/payments/transactions.md
Labels: copy

#292 New home page banner - BITs and Pieces
  _compress_images_cache.yml
  assets/images/home/banner/bits-and-pieces-mobile.png
  assets/images/home/banner/bits-and-pieces-mobile@2x.png
  assets/images/home/banner/bits-and-pieces.png
  assets/images/home/banner/bits-and-pieces@2x.png
  js/themes.js
Labels: dev

#321 Add gallery of screens to the upgradeable wallet case study page
  _compress_images_cache.yml
  assets/images/guide/case-studies/cloud-backup/cloud-backup-preview.jpg
  assets/images/guide/case-studies/multisig-wallet/case-current-mobile.png
  assets/images/guide/case-studies/multisig-wallet/case-current-mobile@2x.png
  assets/images/guide/case-studies/multisig-wallet/case-current.png
  assets/images/guide/case-studies/multisig-wallet/case-current@2x.png
  assets/images/guide/case-studies/multisig-wallet/multisig-wallet-preview.jpg
  assets/images/guide/case-studies/upgradeable-wallet/advanced-options.png
  assets/images/guide/case-studies/upgradeable-wallet/advanced-options@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/backup-info.png
  assets/images/guide/case-studies/upgradeable-wallet/backup-info@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/case-upgradeable-mobile.png
  assets/images/guide/case-studies/upgradeable-wallet/case-upgradeable-mobile@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/case-upgradeable.png
  assets/images/guide/case-studies/upgradeable-wallet/case-upgradeable@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/change-private-key-scheme.png
  assets/images/guide/case-studies/upgradeable-wallet/change-private-key-scheme@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/export-wallet.png
  assets/images/guide/case-studies/upgradeable-wallet/export-wallet@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/first.png
  assets/images/guide/case-studies/upgradeable-wallet/first@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/home.png
  assets/images/guide/case-studies/upgradeable-wallet/home@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/import-wallet.png
  assets/images/guide/case-studies/upgradeable-wallet/import-wallet@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/input-recovery-phrase.png
  assets/images/guide/case-studies/upgradeable-wallet/input-recovery-phrase@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/more-information.png
  assets/images/guide/case-studies/upgradeable-wallet/more-information@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/recovery-phrase.png
  assets/images/guide/case-studies/upgradeable-wallet/recovery-phrase@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/second.png
  assets/images/guide/case-studies/upgradeable-wallet/second@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/settings.png
  assets/images/guide/case-studies/upgradeable-wallet/settings@2x.png
  assets/images/guide/case-studies/upgradeable-wallet/upgradeable-wallet-preview.jpg
  guide/case-studies/cloud-backup.md
  guide/case-studies/multisig-wallet.md
  guide/case-studies/upgradeable-wallet.md
Labels: copy, design

#322 Add gallery of screens to the shared account case study page
  _compress_images_cache.yml
  assets/images/guide/case-studies/shared-account/backup-info.png
  assets/images/guide/case-studies/shared-account/backup-info@2x.png
  assets/images/guide/case-studies/shared-account/case-shared-mobile.png
  assets/images/guide/case-studies/shared-account/case-shared-mobile@2x.png
  assets/images/guide/case-studies/shared-account/case-shared.png
  assets/images/guide/case-studies/shared-account/case-shared@2x.png
  assets/images/guide/case-studies/shared-account/change-private-key-scheme.png
  assets/images/guide/case-studies/shared-account/change-private-key-scheme@2x.png
  assets/images/guide/case-studies/shared-account/continue-later.png
  assets/images/guide/case-studies/shared-account/continue-later@2x.png
  assets/images/guide/case-studies/shared-account/create-multi-key-wallet.png
  assets/images/guide/case-studies/shared-account/create-multi-key-wallet@2x.png
  assets/images/guide/case-studies/shared-account/create-recovery-key.png
  assets/images/guide/case-studies/shared-account/create-recovery-key@2x.png
  assets/images/guide/case-studies/shared-account/create-signing-key.png
  assets/images/guide/case-studies/shared-account/create-signing-key@2x.png
  assets/images/guide/case-studies/shared-account/creation-complete.png
  assets/images/guide/case-studies/shared-account/creation-complete@2x.png
  assets/images/guide/case-studies/shared-account/export-wallet.png
  assets/images/guide/case-studies/shared-account/export-wallet@2x.png
  assets/images/guide/case-studies/shared-account/first.png
  assets/images/guide/case-studies/shared-account/first@2x.png
  assets/images/guide/case-studies/shared-account/home.png
  assets/images/guide/case-studies/shared-account/home@2x.png
  assets/images/guide/case-studies/shared-account/import-multi-key.png
  assets/images/guide/case-studies/shared-account/import-multi-key@2x.png
  assets/images/guide/case-studies/shared-account/import-wallet.png
  assets/images/guide/case-studies/shared-account/import-wallet@2x.png
  assets/images/guide/case-studies/shared-account/input-recovery-phrase.png
  assets/images/guide/case-studies/shared-account/input-recovery-phrase@2x.png
  assets/images/guide/case-studies/shared-account/more-information.png
  assets/images/guide/case-studies/shared-account/more-information@2x.png
  assets/images/guide/case-studies/shared-account/recover-wallet.png
  assets/images/guide/case-studies/shared-account/recover-wallet@2x.png
  assets/images/guide/case-studies/shared-account/recovery-key-setup.png
  assets/images/guide/case-studies/shared-account/recovery-key-setup@2x.png
  assets/images/guide/case-studies/shared-account/replace-key.png
  assets/images/guide/case-studies/shared-account/replace-key@2x.png
  assets/images/guide/case-studies/shared-account/second.png
  assets/images/guide/case-studies/shared-account/second@2x.png
  assets/images/guide/case-studies/shared-account/settings.png
  assets/images/guide/case-studies/shared-account/settings@2x.png
  assets/images/guide/case-studies/shared-account/shared-account-preview.jpg
  guide/case-studies/shared-account.md
Labels: copy, design

#323 Fix various social preview images
  _compress_images_cache.yml
  assets/images/guide/case-studies/page-case-studies.jpg
  assets/images/guide/onboarding/getting-to-know-your-users/getting-to-know-your-users-preview.jpg
  assets/images/guide/payments/payments-preview.jpg
  assets/images/guide/private-key-management/backups/page-backups.jpg
  assets/images/guide/private-key-management/page-private-key-management.jpg
  assets/images/guide/private-key-management/private-key-management-preview.jpg
  assets/images/guide/private-key-management/schemes/page-personal-schemes.jpg
  assets/images/guide/private-key-management/schemes/page-private-key-schemes.jpg
  guide/case-studies/introduction.md
  guide/case-studies/upgradeable-wallet.md
  guide/onboarding/getting-to-know-your-users.md
  guide/payments/introduction.md
  guide/private-key-management/introduction.md
Labels: design

#328 Revise call-to-actions on the home page
  _includes/home-banner.html
  contribute.md
  index.md
Labels: copy

#332 Cross-referencing the cloud backup case study page
  guide/case-studies/cloud-backup.md
  guide/getting-started/personal-finance.md
  guide/getting-started/why-bitcoin-is-unique.md
  guide/getting-started/why-design-for-bitcoin.md
  guide/private-key-management/backups.md
  guide/private-key-management/cloud-backup.md
Labels: copy

#329 Updated table of content formatting on several pages
  _sass/minima/_glossary-page.scss
  guide/contribute/formatting.md
  guide/foundations/principles.md
  guide/getting-started/common-user-flows.md
  guide/getting-started/personal-finance.md
Labels: design

#302 Adds multiple pages to the Onboarding chapter
  _compress_images_cache.yml
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-PIN.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-PIN@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-confirmation.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-confirmation@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-intro.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-intro@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-provider.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-provider@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-service.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/automatic-cloud-backup/cloud-backup-service@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/copy-recovery-phrase.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/copy-recovery-phrase@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/confirm-recovery-phrase-columns.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/confirm-recovery-phrase-columns@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/confirm-recovery-phrase-entry.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/confirm-recovery-phrase-entry@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/confirm-recovery-phrase.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/confirm-recovery-phrase@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-all-at-once.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-all-at-once@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-columns.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-columns@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-reveal.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-reveal@2x.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-single-word.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/manual-backup/copy-recovery-phrase-single-word@2x.png
  assets/images/guide/onboarding/funding-a-wallet/bitcoin-gift-cards.png
  assets/images/guide/onboarding/funding-a-wallet/bitcoin-gift-cards@2x.png
  assets/images/guide/onboarding/funding-a-wallet/buy-bitcoin.png
  assets/images/guide/onboarding/funding-a-wallet/buy-bitcoin@2x.png
  assets/images/guide/onboarding/protecting-a-wallet/choose-pin.png
  assets/images/guide/onboarding/protecting-a-wallet/choose-pin@2x.png
  assets/images/guide/onboarding/protecting-a-wallet/enter-pin.png
  assets/images/guide/onboarding/protecting-a-wallet/enter-pin@2x.png
  assets/images/guide/onboarding/protecting-a-wallet/face-id-info.png
  assets/images/guide/onboarding/protecting-a-wallet/face-id-info@2x.png
  assets/images/guide/onboarding/protecting-a-wallet/hide-by-default.gif
  assets/images/guide/onboarding/protecting-a-wallet/hide-by-eye-icon-2.gif
  assets/images/guide/onboarding/protecting-a-wallet/hide-by-eye-icon.gif
  assets/images/guide/onboarding/protecting-a-wallet/hide-in-settings.gif
  assets/images/guide/onboarding/protecting-a-wallet/hide-info-hidden-by-default.png
  assets/images/guide/onboarding/protecting-a-wallet/hide-info-reveal-by-pin.png
  assets/images/guide/onboarding/protecting-a-wallet/hide-sensitive-information-header.png
  assets/images/guide/onboarding/protecting-a-wallet/reveal-by-pin-2.gif
  assets/images/guide/onboarding/protecting-a-wallet/reveal-by-pin.gif
  assets/images/guide/onboarding/restoring-a-wallet/import-options.png
  assets/images/guide/onboarding/restoring-a-wallet/import-options@2x.png
  guide/onboarding/automatic-cloud-backup.md
  guide/onboarding/backing-up-a-recovery-phrase.md
  guide/onboarding/creating-a-new-wallet.md
  guide/onboarding/funding-a-wallet.md
  guide/onboarding/getting-to-know-your-users.md
  guide/onboarding/introduction.md
  guide/onboarding/manual-backup.md
  guide/onboarding/protecting-a-wallet.md
  guide/onboarding/restoring-a-wallet.md
Labels: copy

#339 Adjusted sidebar scrollbar (fix for #337)
  _sass/minima/_side-bar.scss
  _sass/minima/article/_image-slide-gallery.scss
Labels: dev

#346 Dissolve foundations section, move pages to the Designing Bitcoin Products section
  _compress_images_cache.yml
  assets/images/guide/designing-products/principles/page-principles.jpg
  assets/images/guide/designing-products/principles/principles-mobile.jpg
  assets/images/guide/designing-products/principles/principles-mobile@2x.jpg
  assets/images/guide/designing-products/principles/principles.jpg
  assets/images/guide/designing-products/principles/principles@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/integrations.jpg
  assets/images/guide/designing-products/wallet-interoperability/integrations@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/key-import-export.jpg
  assets/images/guide/designing-products/wallet-interoperability/key-import-export@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/multi-signature.jpg
  assets/images/guide/designing-products/wallet-interoperability/multi-signature@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/node-options.jpg
  assets/images/guide/designing-products/wallet-interoperability/node-options@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/payment-links.jpg
  assets/images/guide/designing-products/wallet-interoperability/payment-links@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/qr-code.jpg
  assets/images/guide/designing-products/wallet-interoperability/qr-code@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/transaction-file.jpg
  assets/images/guide/designing-products/wallet-interoperability/transaction-file@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/user-data-import-export.jpg
  assets/images/guide/designing-products/wallet-interoperability/user-data-import-export@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/wallet-interoperability-mobile.jpg
  assets/images/guide/designing-products/wallet-interoperability/wallet-interoperability-mobile@2x.jpg
  assets/images/guide/designing-products/wallet-interoperability/wallet-interoperability-preview.jpg
  assets/images/guide/designing-products/wallet-interoperability/wallet-interoperability.jpg
  assets/images/guide/designing-products/wallet-interoperability/wallet-interoperability@2x.jpg
  assets/images/guide/foundations/foundations-preview.jpg
  guide/designing-products/common-user-flows.md
  guide/designing-products/designing-products.md
  guide/designing-products/open-design.md
  guide/designing-products/personal-finance.md
  guide/designing-products/principles.md
  guide/designing-products/usage-life-cycle.md
  guide/designing-products/user-research.md
  guide/designing-products/wallet-interoperability.md
  guide/foundations/foundations.md
Labels: copy

#345 Add formatting info for link preview images
  guide/contribute/illustration-guidelines.md
  guide/onboarding/manual-backup.md
Labels: copy

#342 Turns scheme illustrations in content to page header images
  _compress_images_cache.yml
  assets/images/guide/private-key-management/cloud-backup/cloud-backup-mobile.jpg
  assets/images/guide/private-key-management/cloud-backup/cloud-backup-mobile@2x.jpg
  assets/images/guide/private-key-management/cloud-backup/cloud-backup-preview.jpg
  assets/images/guide/private-key-management/cloud-backup/cloud-backup.jpg
  assets/images/guide/private-key-management/cloud-backup/cloud-backup@2x.jpg
  assets/images/guide/private-key-management/external-signing-device/external-signing-device-mobile.png
  assets/images/guide/private-key-management/external-signing-device/external-signing-device-mobile@2x.png
  assets/images/guide/private-key-management/external-signing-device/external-signing-device-preview.png
  assets/images/guide/private-key-management/external-signing-device/external-signing-device.png
  assets/images/guide/private-key-management/external-signing-device/external-signing-device@2x.png
  assets/images/guide/private-key-management/key-sharing/key-sharing-mobile.png
  assets/images/guide/private-key-management/key-sharing/key-sharing-mobile@2x.png
  assets/images/guide/private-key-management/key-sharing/key-sharing-preview.png
  assets/images/guide/private-key-management/key-sharing/key-sharing.png
  assets/images/guide/private-key-management/key-sharing/key-sharing@2x.png
  assets/images/guide/private-key-management/manual-backup/manual-backup-mobile.png
  assets/images/guide/private-key-management/manual-backup/manual-backup-mobile@2x.png
  assets/images/guide/private-key-management/manual-backup/manual-backup-preview.png
  assets/images/guide/private-key-management/manual-backup/manual-backup.png
  assets/images/guide/private-key-management/manual-backup/manual-backup@2x.png
  assets/images/guide/private-key-management/multi-key/multi-key-mobile.png
  assets/images/guide/private-key-management/multi-key/multi-key-mobile@2x.png
  assets/images/guide/private-key-management/multi-key/multi-key-preview.png
  assets/images/guide/private-key-management/multi-key/multi-key.png
  assets/images/guide/private-key-management/multi-key/multi-key@2x.png
  guide/private-key-management/cloud-backup.md
  guide/private-key-management/external-signing-device.md
  guide/private-key-management/manual-backup.md
  guide/private-key-management/multi-key.md
  guide/private-key-management/threshold-signatures.md
Labels: design

#344 Fix for #288 - created header image for Visual Language page
  _compress_images_cache.yml
  assets/images/guide/getting-started/visual-language/bitcoin-visual-language-mobile.jpg
  assets/images/guide/getting-started/visual-language/bitcoin-visual-language-mobile@2x.jpg
  assets/images/guide/getting-started/visual-language/bitcoin-visual-language.jpg
  assets/images/guide/getting-started/visual-language/bitcoin-visual-language@2x.jpg
  assets/images/guide/getting-started/visual-language/visual-language-preview.jpg
  guide/getting-started/visual-language.md
Labels: design

#314 Rename 'Checking account' page to 'Savings account.'
  guide/case-studies/savings-account.md
Labels: copy

#347 Fixing various broken links
  guide.md
  guide/case-studies/introduction.md
  guide/designing-products/open-design.md
  guide/designing-products/personal-finance.md
  guide/designing-products/user-research.md
  guide/glossary.md
  guide/onboarding/automatic-cloud-backup.md
  guide/onboarding/getting-to-know-your-users.md
  guide/onboarding/restoring-a-wallet.md
  guide/payments/receive.md
  guide/payments/send.md
Labels: bug

#351 Added various links to the savings account case study
  guide/case-studies/savings-account.md
Labels: copy

#353 Added various links to the shared account case study
  guide/case-studies/shared-account.md
Labels: copy

#352 Added various links to the upgradable account case study
  guide/case-studies/upgradeable-wallet.md
Labels: copy

#354 Add missing link to bottom of 'propose a change' page.
  guide/contribute/propose-a-change.md
Labels: copy

#308 Add nitpick checklist for writers in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: copy

#356 Update visual-language.md
  guide/getting-started/visual-language.md
Labels: copy

#349 Create transaction privacy page #175
  _compress_images_cache.yml
  assets/images/guide/payments/privacy/address-labeling.jpg
  assets/images/guide/payments/privacy/address-labeling@2x.jpg
  assets/images/guide/payments/privacy/coin-join.jpg
  assets/images/guide/payments/privacy/coin-join@2x.jpg
  assets/images/guide/payments/privacy/header.jpg
  assets/images/guide/payments/privacy/header@2x.jpg
  assets/images/guide/payments/privacy/privacy-header-mobile.jpg
  assets/images/guide/payments/privacy/privacy-header-mobile@2x.jpg
  assets/images/guide/payments/privacy/privacy-preview.jpg
  guide/payments/introduction.md
  guide/payments/privacy.md
  guide/payments/receive.md
Labels: copy, payments
