Repository BitcoinDesign/Guide, pull requests merged in 2021-04, with the labels that each got.

#216 Adds styling for definition list for the new pages in the onboarding section
  _includes/dl/close.html
  _includes/dl/item-close.html
  _includes/dl/item-middle.html
  _includes/dl/item-open.html
  _includes/dl/item.html
  _includes/dl/open.html
  _includes/svgs.html
  _sass/minima/_article.scss
  _sass/minima/_variables.scss
  guide/contribute/formatting.md
Labels: dev

#215 Tip and fact template cleanup
  _includes/fact-cons.html
  _includes/fact-products.html
  _includes/fact-pros.html
  _includes/fact-variations.html
  _includes/fact-when-not-to-use.html
  _includes/fact-when-to-use.html
  _includes/fact/close.html
  _includes/fact/cons.html
  _includes/fact/donts.html
  _includes/fact/dos.html
  _includes/fact/open.html
  _includes/fact/products.html
  _includes/fact/pros.html
  _includes/fact/variations.html
  _includes/fact/when-not-to-use.html
  _includes/fact/when-to-use.html
  _includes/rec-open.html
  _includes/tip-close.html
  _includes/tip-open.html
  _includes/tip/close.html
  _includes/tip/open.html
  _includes/tip/recommendation.html
  _includes/tip/tip.html
  _sass/minima/_article.scss
  guide/contribute/formatting.md
  guide/private-key-management/single-user-schemes.md
Labels: dev

#214 Adds blockquote component
  _sass/minima/_base.scss
  guide/contribute/formatting.md
Labels: dev

#219 Additional style options for the image component
  _sass/minima/_article.scss
Labels: dev

#227 Adding missing div to fix broken layout on desktop on the software page
  guide/getting-started/software.md
Labels: bug, dev

#230 Fixes missing first character of blockquotes
  _sass/minima/_base.scss
Labels: bug, dev

#197 Test for fixing canonical URLs
  _config.yml
  index.md
Labels: dev

#186 add docker.compose.yml
  Gemfile.lock
  README.md
  docker-compose.yml
Labels: dev

#218 Link pages to principles
  guide/foundations/wallet-interoperability.md
  guide/getting-started/open-design.md
  guide/getting-started/personal-finance.md
  guide/getting-started/user-research.md
  guide/glossary.md
  guide/onboarding/getting-to-know-your-users.md
  guide/private-key-management/multi-user-schemes.md
Labels: copy

#224 Update contribute.md
  guide/contribute/contribute.md
Labels: copy

#232 Add link to bitcoinicons.com to the projects page
  projects.md
Labels: copy

#236 Update send.md
  guide/payments/send.md
Labels: copy, payments

#234 Optimizing unnecessarily huge images
  _compress_images_cache.yml
  assets/images/guide/getting-started/technology/blueprint-mobile.jpg
  assets/images/guide/getting-started/technology/blueprint-mobile.png
  assets/images/guide/getting-started/technology/blueprint-mobile@2x.jpg
  assets/images/guide/getting-started/technology/blueprint-mobile@2x.png
  assets/images/guide/getting-started/technology/blueprint.jpg
  assets/images/guide/getting-started/technology/blueprint.png
  assets/images/guide/getting-started/technology/blueprint@2x.jpg
  assets/images/guide/getting-started/technology/blueprint@2x.png
  assets/images/guide/onboarding/getting-to-know-your-users-mobile.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users-mobile@2x.jpeg
  assets/images/guide/onboarding/onboarding-mobile.png
  assets/images/guide/onboarding/onboarding-mobile@2x.png
  assets/images/guide/onboarding/onboarding-preview.png
  assets/images/guide/onboarding/onboarding.png
  assets/images/guide/onboarding/onboarding@2x.png
  assets/images/guide/payments/transactions/transactions-desktop.jpg
  assets/images/guide/payments/transactions/transactions-desktop.png
  assets/images/guide/payments/transactions/transactions-desktop@2x.jpg
  assets/images/guide/payments/transactions/transactions-desktop@2x.png
  assets/images/guide/payments/transactions/transactions-mobile.jpg
  assets/images/guide/payments/transactions/transactions-mobile.png
  assets/images/guide/payments/transactions/transactions-mobile@2x.jpg
  assets/images/guide/payments/transactions/transactions-mobile@2x.png
  guide/getting-started/technology-primer.md
  guide/onboarding/introduction.md
  guide/payments/transactions.md
Labels: dev

#237 Adds the visual Do and Don't component
  _includes/do/close.html
  _includes/do/middle.html
  _includes/do/open.html
  _includes/do/single-close.html
  _includes/do/single-open.html
  _sass/minima/_article.scss
  guide/contribute/formatting.md
Labels: dev

#235 Addressing various accessibility issues
  _includes/header.html
  _includes/home-banner.html
  _includes/secondary-nav.html
  _layouts/default.html
  _layouts/guide.html
  _sass/minima/_nav-list.scss
Labels: dev

#241 Fixes layout issue for long text in the image slide gallery component
  _sass/minima/_article.scss
  guide/contribute/formatting.md
Labels: dev

#258 Changing absolute URLs in the nav and search includes
  _includes/head.html
  _includes/secondary-nav.html
  search-data.json
Labels: dev

#251 Feature/inputs outputs image
  assets/images/guide/payments/transactions/inputs-and-outputs-mobile.svg
  assets/images/guide/payments/transactions/inputs-and-outputs.svg
  guide/payments/transactions.md
Labels: design

#238 Update why-bitcoin-is-unique.md
  guide/getting-started/why-bitcoin-is-unique.md
Labels: copy

#252 Replace box-shadow with drop-shadow filter
  _sass/minima/_article.scss
Labels: dev

#263 Minor addition to target audience paragraph in content guidelines
  guide/contribute/content-guidelines.md
Labels: copy

#220 Update guide.md
  guide.md
Labels: copy

#270 Update UI kit examples on the common user flows page
  _compress_images_cache.yml
  assets/images/guide/getting-started/common-user-flows/receiving-ui-example-enter-info.png
  assets/images/guide/getting-started/common-user-flows/receiving-ui-example-enter-info@2x.png
  assets/images/guide/getting-started/common-user-flows/receiving-ui-example-share-request.png
  assets/images/guide/getting-started/common-user-flows/receiving-ui-example-share-request@2x.png
  assets/images/guide/getting-started/common-user-flows/receiving-ui-example.jpg
  assets/images/guide/getting-started/common-user-flows/receiving-ui-example@2x.jpg
  assets/images/guide/getting-started/common-user-flows/sending-ui-basic.png
  assets/images/guide/getting-started/common-user-flows/sending-ui-basic@2x.png
  assets/images/guide/getting-started/common-user-flows/sending-ui-complex.png
  assets/images/guide/getting-started/common-user-flows/sending-ui-complex@2x.png
  assets/images/guide/getting-started/common-user-flows/sending-ui-complexity.jpg
  assets/images/guide/getting-started/common-user-flows/sending-ui-complexity@2x.jpg
  guide/getting-started/common-user-flows.md
Labels: copy, design
