Repository BitcoinDesign/Guide, pull requests merged in 2021-03, with the labels that each got.

#167 Added Twitter, Youtube and top-level links to the footer
  _config.yml
  _includes/footer.html
  _includes/social.html
  _includes/twitter.svg
  _includes/youtube.svg
  _sass/minima/_site-footer.scss
Labels: copy, dev

#164 Revise the "Contribute to guide" section landing page
  contribute.md
  guide/contribute/contribute.md
Labels: copy

#161 Moves case studies from Private Key section to a dedicated section
  _compress_images_cache.yml
  assets/images/guide/case-studies/case-cash-mobile.png
  assets/images/guide/case-studies/case-cash-mobile@2x.png
  assets/images/guide/case-studies/case-cash.png
  assets/images/guide/case-studies/case-cash@2x.png
  assets/images/guide/case-studies/case-current-mobile.png
  assets/images/guide/case-studies/case-current-mobile@2x.png
  assets/images/guide/case-studies/case-current.png
  assets/images/guide/case-studies/case-current@2x.png
  assets/images/guide/case-studies/case-shared-mobile.png
  assets/images/guide/case-studies/case-shared-mobile@2x.png
  assets/images/guide/case-studies/case-shared.png
  assets/images/guide/case-studies/case-shared@2x.png
  assets/images/guide/case-studies/case-studies-mobile.jpg
  assets/images/guide/case-studies/case-studies-mobile@2x.jpg
  assets/images/guide/case-studies/case-studies.jpg
  assets/images/guide/case-studies/case-studies@2x.jpg
  assets/images/guide/case-studies/case-upgradeable-mobile.png
  assets/images/guide/case-studies/case-upgradeable-mobile@2x.png
  assets/images/guide/case-studies/case-upgradeable.png
  assets/images/guide/case-studies/case-upgradeable@2x.png
  assets/images/guide/case-studies/page-case-studies.jpg
  guide.md
  guide/case-studies/cloud-backup.md
  guide/case-studies/introduction.md
  guide/case-studies/multisig-wallet.md
  guide/case-studies/shared-account.md
  guide/case-studies/upgradeable-wallet.md
  guide/private-key-management/case-studies.md
  guide/private-key-management/introduction.md
  guide/private-key-management/principles.md
Labels: copy

#166 Adds formatting for image galleries, recommendations, tips, and facts
  _compress_images_cache.yml
  _includes/fact-close.html
  _includes/fact-cons.html
  _includes/fact-open.html
  _includes/fact-products.html
  _includes/fact-pros.html
  _includes/fact-variations.html
  _includes/fact-when-not-to-use.html
  _includes/fact-when-to-use.html
  _includes/rec-close.html
  _includes/rec-open.html
  _includes/svgs.html
  _includes/tip-close.html
  _includes/tip-open.html
  _sass/minima/_article.scss
  _sass/minima/_variables.scss
  assets/images/guide/contribute/formatting/example-image-mobile-screen.png
  assets/images/guide/contribute/formatting/example-image-mobile-screen@2x.png
  assets/images/guide/contribute/formatting/example-image-square.jpg
  assets/images/guide/contribute/formatting/example-image-square@2x.jpg
  assets/images/guide/contribute/formatting/example-image-wide-desktop.jpg
  assets/images/guide/contribute/formatting/example-image-wide-desktop@2x.jpg
  assets/images/guide/contribute/formatting/example-image-wide-mobile.jpg
  assets/images/guide/contribute/formatting/example-image-wide-mobile@2x.jpg
  guide/contribute/formatting.md
Labels: design, dev

#180 Adds the guide landing page to the secondary nav as "Introduction"
  _includes/secondary-nav.html
  guide.md
  guide/case-studies/introduction.md
  guide/foundations/foundations.md
  guide/getting-started/getting-started.md
  guide/glossary.md
  guide/onboarding/introduction.md
  guide/payments/introduction.md
  guide/private-key-management/introduction.md
Labels: copy

#178 Adds a table of contents to the glossary page
  _sass/minima/_glossary-page.scss
  _sass/minima/initialize.scss
  guide/glossary.md
Labels: copy

#170 Grammar improvements and simplifications in the Getting Started Section
  guide/getting-started/common-user-flows.md
  guide/getting-started/getting-started.md
  guide/getting-started/hardware.md
  guide/getting-started/open-design.md
  guide/getting-started/personal-finance.md
  guide/getting-started/software.md
  guide/getting-started/technology-primer.md
  guide/getting-started/usage-life-cycle.md
  guide/getting-started/user-research.md
  guide/getting-started/visual-language.md
  guide/getting-started/why-bitcoin-is-unique.md
  guide/getting-started/why-design-for-bitcoin.md
Labels: copy

#179 Clarifies text and projects on the Projects page
  _sass/minima/_projects-page.scss
  projects.md
Labels: copy

#184 Fixes visual glitch on the formatting page
  _sass/minima/_article.scss
  _sass/minima/_layout.scss
  guide/contribute/formatting.md
Labels: bug, dev

#189 Adds Bitcoin icon set info to the projects page
  assets/images/contribute/bitcoin-icon-set.svg
  projects.md
Labels: copy

#144 Create unified Bitcoin design principles page
  README.md
  assets/images/guide/foundations/principles/page-principles.jpg
  assets/images/guide/foundations/principles/principles-mobile.jpg
  assets/images/guide/foundations/principles/principles-mobile@2x.jpg
  assets/images/guide/foundations/principles/principles.jpg
  assets/images/guide/foundations/principles/principles@2x.jpg
  guide/contribute/contribute.md
  guide/foundations/foundations.md
  guide/foundations/principles.md
  guide/onboarding/introduction.md
  guide/private-key-management/introduction.md
  guide/private-key-management/multi-user-schemes.md
  guide/private-key-management/principles.md
Labels: copy

#169 Adds the "Getting to know your users" section to the Onboarding chapter
  _compress_images_cache.yml
  assets/images/guide/onboarding/getting-to-know-your-users-mobile.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users-mobile@2x.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users.jpeg
  assets/images/guide/onboarding/getting-to-know-your-users@2x.jpeg
  assets/images/guide/onboarding/highest-motivator-battery.svg
  assets/images/guide/onboarding/lowest-barrier-battery.svg
  assets/images/guide/onboarding/lowest-motivator-battery.svg
  assets/images/guide/onboarding/neutral-barrier-battery.svg
  assets/images/guide/onboarding/neutral-motivator-battery.svg
  assets/images/guide/onboarding/onboarding-mobile.png
  assets/images/guide/onboarding/onboarding-mobile@2x.png
  assets/images/guide/onboarding/onboarding.png
  assets/images/guide/onboarding/onboarding.svg
  assets/images/guide/onboarding/onboarding@2x.png
  assets/images/guide/onboarding/strongest-barrier-battery.svg
  guide/onboarding/getting-to-know-your-users.md
  guide/onboarding/introduction.md
Labels: copy

#194 Ran html proofer and fixed some broken links
  _compress_images_cache.yml
  guide/contribute/content-guidelines.md
  guide/contribute/propose-a-change.md
  guide/private-key-management/introduction.md
  guide/private-key-management/multi-user-schemes.md
  guide/private-key-management/single-user-schemes.md
Labels: dev

#196 Adds placeholder header images for contribute section pages
  _compress_images_cache.yml
  assets/images/guide/contribute/content-guidelines-preview.jpg
  assets/images/guide/contribute/content-guidelines/content-guidelines-header-mobile.png
  assets/images/guide/contribute/content-guidelines/content-guidelines-header-mobile@2x.png
  assets/images/guide/contribute/content-guidelines/content-guidelines-header.png
  assets/images/guide/contribute/content-guidelines/content-guidelines-header@2x.png
  assets/images/guide/contribute/content-guidelines/content-guidelines-mobile.jpg
  assets/images/guide/contribute/content-guidelines/content-guidelines-mobile@2x.jpg
  assets/images/guide/contribute/content-guidelines/content-guidelines-preview.jpg
  assets/images/guide/contribute/content-guidelines/content-guidelines.jpg
  assets/images/guide/contribute/content-guidelines/content-guidelines@2x.jpg
  assets/images/guide/contribute/contribute-mobile.png
  assets/images/guide/contribute/contribute-mobile@2x.png
  assets/images/guide/contribute/contribute-preview.jpg
  assets/images/guide/contribute/contribute.png
  assets/images/guide/contribute/contribute@2x.png
  assets/images/guide/contribute/formatting-preview.jpg
  assets/images/guide/contribute/formatting/formatting-mobile.jpg
  assets/images/guide/contribute/formatting/formatting-mobile@2x.jpg
  assets/images/guide/contribute/formatting/formatting-preview.jpg
  assets/images/guide/contribute/formatting/formatting.jpg
  assets/images/guide/contribute/formatting/formatting@2x.jpg
  assets/images/guide/contribute/propose-a-change/propose-a-change-mobile.jpg
  assets/images/guide/contribute/propose-a-change/propose-a-change-mobile@2x.jpg
  assets/images/guide/contribute/propose-a-change/propose-a-change-preview.jpg
  assets/images/guide/contribute/propose-a-change/propose-a-change.jpg
  assets/images/guide/contribute/propose-a-change/propose-a-change@2x.jpg
  assets/images/guide/contribute/review/review-mobile.jpg
  assets/images/guide/contribute/review/review-mobile@2x.jpg
  assets/images/guide/contribute/review/review-preview.jpg
  assets/images/guide/contribute/review/review.jpg
  assets/images/guide/contribute/review/review@2x.jpg
  guide/contribute/content-guidelines.md
  guide/contribute/contribute.md
  guide/contribute/formatting.md
  guide/contribute/propose-a-change.md
  guide/contribute/review.md
Labels: design

#204 Update Gemfile.lock
  Gemfile.lock
Labels: dev

#206 Fixes list rendering in fact boxes
  _includes/fact-close.html
  _includes/fact-open.html
  _sass/minima/_article.scss
  guide/private-key-management/single-user-schemes.md
Labels: dev
