Repository BitcoinDesign/Guide, pull requests merged in 2021-02, with the labels that each got.

#128 Update - Add mobile friendly versions of spectrum and flow chart (Private key chapter)
  _compress_images_cache.yml
  assets/images/guide/private-key-management/schemes/flow-chart-mobile.png
  assets/images/guide/private-key-management/schemes/flow-chart-mobile@2x.png
  assets/images/guide/private-key-management/schemes/flow-chart.jpg
  assets/images/guide/private-key-management/schemes/flow-chart.png
  assets/images/guide/private-key-management/schemes/flow-chart@2x.jpg
  assets/images/guide/private-key-management/schemes/flow-chart@2x.png
  assets/images/guide/private-key-management/schemes/spectrum-mobile.png
  assets/images/guide/private-key-management/schemes/spectrum-mobile@2x.png
  assets/images/guide/private-key-management/schemes/spectrum.jpg
  assets/images/guide/private-key-management/schemes/spectrum.png
  assets/images/guide/private-key-management/schemes/spectrum@2x.jpg
  assets/images/guide/private-key-management/schemes/spectrum@2x.png
  guide/private-key-management/schemes.md
Labels: enhancement

#133 Adjust styling of home page banner on mobile
  _includes/banner-bitcoin-logo.svg
  _includes/header.html
  _includes/home-banner.html
  _includes/svgs.html
  _sass/minima/_home-banner.scss
  _sass/minima/_site-header.scss
  _sass/minima/skins/error-theme.scss
Labels: design, dev

#136 Update copy about licensing on the open design page
  guide/getting-started/open-design.md
Labels: copy

#140 Updated table of contents on the guide landing page.
  guide.md
Labels: copy

#138 Remove Figma embed from the "Submit a banner" page
  _compress_images_cache.yml
  _includes/prototype.html
  assets/images/home/banner/figma-preview-mobile.png
  assets/images/home/banner/figma-preview-mobile@2x.png
  assets/images/home/banner/figma-preview.png
  assets/images/home/banner/figma-preview@2x.png
  submit-header-design.md
Labels: dev

#145 Add collaboration info to the Projects page
  _compress_images_cache.yml
  assets/images/contribute/specter.png
  assets/images/contribute/zeus.png
  projects.md
Labels: copy

#155 Add header image to the Projects page
  _compress_images_cache.yml
  _sass/minima/_article.scss
  _sass/minima/_layout.scss
  _sass/minima/_projects-page.scss
  assets/images/projects-preview.jpg
  assets/images/projects/projects-mobile.jpg
  assets/images/projects/projects-mobile@2x.jpg
  assets/images/projects/projects-preview.jpg
  assets/images/projects/projects.jpg
  assets/images/projects/projects@2x.jpg
  projects.md
Labels: design

#163 Adds header and preview images to the glossary
  _compress_images_cache.yml
  assets/images/guide/glossary/glossary-mobile.png
  assets/images/guide/glossary/glossary-mobile@2x.png
  assets/images/guide/glossary/glossary-preview.jpg
  assets/images/guide/glossary/glossary.png
  assets/images/guide/glossary/glossary@2x.png
  guide/glossary.md
Labels: design
