Repository BitcoinDesign/Guide, pull requests merged in 2021-06, with the labels that each got.

#380 Fix header images on the Designing Bitcoin Products page
  assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-mobile.png
  assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-mobile@2x.png
  assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-preview.png
  assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-web.png
  assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-web@2x.png
  guide/designing-products/designing-products.md
Labels: dev

#387 Minor fix: Add missing break line on getting to know your users
  guide/onboarding/getting-to-know-your-users.md
Labels: design

#394 Update formatting.md
  guide/contribute/formatting.md
Labels: copy

#396 Update review.md
  guide/contribute/review.md
Labels: copy

#384 Update issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---content-request.md
  .github/ISSUE_TEMPLATE/---image-request.md
Labels: enhancement

#395 Update content-guidelines.md
  guide/contribute/content-guidelines.md
Labels: copy

#375 Update usage-life-cycle.md
  guide/designing-products/usage-life-cycle.md
Labels: copy

#381 Added page for collecting user research references
  _compress_images_cache.yml
  assets/images/guide/designing-products/user-research-resources/user-research-resources-mobile.jpg
  assets/images/guide/designing-products/user-research-resources/user-research-resources-mobile@2x.jpg
  assets/images/guide/designing-products/user-research-resources/user-research-resources-preview.jpg
  assets/images/guide/designing-products/user-research-resources/user-research-resources.jpg
  assets/images/guide/designing-products/user-research-resources/user-research-resources@2x.jpg
  guide/designing-products/user-research-resources.md
  guide/designing-products/user-research.md
Labels: copy

#365 Update user-research.md
  guide/designing-products/user-research.md
Labels: copy

#374 Update Personal Finance
  guide/designing-products/personal-finance.md
Labels: copy

#405 Reworded blockchain to ledger from database
  guide/getting-started/technology-primer.md
Labels: copy

#409 Fix to add 💪 to a weak site description
  _config.yml
Labels: copy

#404 Update Readme
  README.md
Labels: copy

#410 Make address + wallet content sub pages of glossary with read more links
  guide/glossary/address.md
  guide/glossary/index.md
  guide/glossary/wallet.md
Labels: copy

#406 Added missing SEO description tags and H1 title fix
  guide/case-studies/cloud-backup.md
  guide/case-studies/savings-account.md
  guide/case-studies/shared-account.md
  guide/case-studies/upgradeable-wallet.md
  guide/designing-products/common-user-flows.md
  guide/designing-products/designing-products.md
  guide/designing-products/open-design.md
  guide/designing-products/personal-finance.md
  guide/designing-products/usage-life-cycle.md
  guide/designing-products/user-research.md
  guide/designing-products/why-design-for-bitcoin.md
  guide/getting-started/getting-started.md
  guide/getting-started/hardware.md
  guide/getting-started/software.md
  guide/getting-started/technology-primer.md
  guide/getting-started/visual-language.md
  guide/getting-started/why-bitcoin-is-unique.md
  guide/onboarding/automatic-cloud-backup.md
  guide/onboarding/backing-up-a-recovery-phrase.md
  guide/onboarding/creating-a-new-wallet.md
  guide/onboarding/funding-a-wallet.md
  guide/onboarding/manual-backup.md
  guide/onboarding/protecting-a-wallet.md
  guide/onboarding/restoring-a-wallet.md
  guide/payments/coin-selection.md
  guide/private-key-management/cloud-backup.md
  guide/private-key-management/external-signing-device.md
  guide/private-key-management/introduction.md
  guide/private-key-management/manual-backup.md
  guide/private-key-management/multi-key.md
Labels: copy

#414 Fix various image-related minor issues on the coin selection page
  _compress_images_cache.yml
  assets/images/guide/case-studies/multisig-wallet/change-private-key-scheme.png
  assets/images/guide/case-studies/multisig-wallet/change-private-key-scheme@2x.png
  assets/images/guide/glossary/coin-selection/header-mobile@2x.jpg
  assets/images/guide/glossary/coin-selection/header.jpg
  assets/images/guide/glossary/coin-selection/header@2x.jpg
  assets/images/guide/payments/coin-selection/auto.png
  assets/images/guide/payments/coin-selection/auto@2x.png
  assets/images/guide/payments/coin-selection/automatic-algorithms/blackjack.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/blackjack@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/bnb.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/bnb@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/fifo.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/fifo@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/high-priority-first.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/high-priority-first@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/lifo.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/lifo@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/minimise-fees-merge-coins.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/minimise-fees-merge-coins@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/minimise-fees-optimising-size.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/minimise-fees-optimising-size@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/pruned-fifo.jpg
  assets/images/guide/payments/coin-selection/automatic-algorithms/pruned-fifo@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-coin-selection-mobile.jpg
  assets/images/guide/payments/coin-selection/automatic-coin-selection-mobile@2x.jpg
  assets/images/guide/payments/coin-selection/automatic-coin-selection.jpg
  assets/images/guide/payments/coin-selection/automatic-coin-selection@2x.jpg
  assets/images/guide/payments/coin-selection/coin-selection-preview.jpg
  assets/images/guide/payments/coin-selection/coins.png
  assets/images/guide/payments/coin-selection/coins@2x.png
  assets/images/guide/payments/coin-selection/freezing-mobile.jpg
  assets/images/guide/payments/coin-selection/freezing-mobile@2x.jpg
  assets/images/guide/payments/coin-selection/freezing.jpg
  assets/images/guide/payments/coin-selection/freezing@2x.jpg
  assets/images/guide/payments/coin-selection/funding-tx-mobile.jpg
  assets/images/guide/payments/coin-selection/funding-tx-mobile@2x.jpg
  assets/images/guide/payments/coin-selection/funding-tx.jpg
  assets/images/guide/payments/coin-selection/funding-tx@2x.jpg
  assets/images/guide/payments/coin-selection/header-mobile.jpg
  assets/images/guide/payments/coin-selection/header-mobile@2x.jpg
  assets/images/guide/payments/coin-selection/header.jpg
  assets/images/guide/payments/coin-selection/header@2x.jpg
  assets/images/guide/payments/coin-selection/home.png
  assets/images/guide/payments/coin-selection/home@2x.png
  assets/images/guide/payments/coin-selection/manual-coin-selection-mobile.jpg
  assets/images/guide/payments/coin-selection/manual-coin-selection-mobile@2x.jpg
  assets/images/guide/payments/coin-selection/manual-coin-selection.jpg
  assets/images/guide/payments/coin-selection/manual-coin-selection@2x.jpg
  assets/images/guide/payments/coin-selection/manual.png
  assets/images/guide/payments/coin-selection/manual@2x.png
  assets/images/guide/payments/coin-selection/review.png
  assets/images/guide/payments/coin-selection/review@2x.png
  assets/images/guide/payments/coin-selection/send-details.png
  assets/images/guide/payments/coin-selection/send-details@2x.png
  assets/images/guide/payments/coin-selection/sent.png
  assets/images/guide/payments/coin-selection/sent@2x.png
  guide/payments/coin-selection.md
Labels: dev
