Repository BitcoinDesign/Guide, pull requests merged in 2021-09, with the labels that each got.

#457 Updated 'onboarding/Backing up recovery phrase' image
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/copy-recovery-phrase.png
  assets/images/guide/onboarding/backing-up-a-recovery-phrase/copy-recovery-phrase@2x.png
  guide/onboarding/backing-up-a-recovery-phrase.md
Labels: design

#63 Add a Units and Symbols Page
  _compress_images_cache.yml
  assets/images/guide/payments/units-and-symbols/enter-amount.png
  assets/images/guide/payments/units-and-symbols/enter-amount@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-digit-groups-mobile.png
  assets/images/guide/payments/units-and-symbols/formatting-digit-groups-mobile@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-digit-groups.png
  assets/images/guide/payments/units-and-symbols/formatting-digit-groups@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-elements.png
  assets/images/guide/payments/units-and-symbols/formatting-elements@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-monospace-mobile.png
  assets/images/guide/payments/units-and-symbols/formatting-monospace-mobile@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-monospace.png
  assets/images/guide/payments/units-and-symbols/formatting-monospace@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-slashed-zeros-mobile.png
  assets/images/guide/payments/units-and-symbols/formatting-slashed-zeros-mobile@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-slashed-zeros.png
  assets/images/guide/payments/units-and-symbols/formatting-slashed-zeros@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-trailing-zeros-mobile.png
  assets/images/guide/payments/units-and-symbols/formatting-trailing-zeros-mobile@2x.png
  assets/images/guide/payments/units-and-symbols/formatting-trailing-zeros.png
  assets/images/guide/payments/units-and-symbols/formatting-trailing-zeros@2x.png
  assets/images/guide/payments/units-and-symbols/home-unit-bitcoin.png
  assets/images/guide/payments/units-and-symbols/home-unit-bitcoin@2x.png
  assets/images/guide/payments/units-and-symbols/home-unit-hidden.png
  assets/images/guide/payments/units-and-symbols/home-unit-hidden@2x.png
  assets/images/guide/payments/units-and-symbols/home-unit-options.png
  assets/images/guide/payments/units-and-symbols/home-unit-options@2x.png
  assets/images/guide/payments/units-and-symbols/home-unit-sats.png
  assets/images/guide/payments/units-and-symbols/home-unit-sats@2x.png
  assets/images/guide/payments/units-and-symbols/settings-bitcoin-units.png
  assets/images/guide/payments/units-and-symbols/settings-bitcoin-units@2x.png
  assets/images/guide/payments/units-and-symbols/settings-local-currency.png
  assets/images/guide/payments/units-and-symbols/settings-local-currency@2x.png
  assets/images/guide/payments/units-and-symbols/settings.png
  assets/images/guide/payments/units-and-symbols/settings@2x.png
  assets/images/guide/payments/units-and-symbols/units-and-symbols-mobile.png
  assets/images/guide/payments/units-and-symbols/units-and-symbols-mobile@2x.png
  assets/images/guide/payments/units-and-symbols/units-and-symbols-preview.jpg
  assets/images/guide/payments/units-and-symbols/units-and-symbols.png
  assets/images/guide/payments/units-and-symbols/units-and-symbols@2x.png
  guide/case-studies/introduction.md
  guide/payments/introduction.md
  guide/payments/privacy.md
  guide/payments/units-and-symbols.md
Labels: payments, copy, design

#479 Add Disclaimer about Lightning WIP to Guide intro page
  guide.md
  guide/glossary/index.md
Labels: copy

#477 Added ⚡️ content to `Getting Started` > `Why bitcoin is unique`
  _compress_images_cache.yml
  assets/images/guide/getting-started/why-bitcoin-is-unique/equality.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/equality@2x.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/internet-money.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/internet-money@2x.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/supply.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/supply@2x.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/why-bitcoin-is-unique-mobile.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/why-bitcoin-is-unique-mobile@2x.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/why-bitcoin-is-unique-preview.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/why-bitcoin-is-unique.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/why-bitcoin-is-unique@2x.jpg
  guide/getting-started/why-bitcoin-is-unique.md
Labels: copy, design

#475 Added ⚡️ content to `Getting Started` > `Visual language`
  _compress_images_cache.yml
  assets/images/guide/getting-started/visual-language/bitcoin-lightning-branding.jpg
  assets/images/guide/getting-started/visual-language/bitcoin-lightning-branding@2x.jpg
  assets/images/guide/getting-started/visual-language/bitcoin-symbol.png
  assets/images/guide/getting-started/visual-language/bitcoin-symbol.svg
  assets/images/guide/getting-started/visual-language/satoshi-symbols.png
  assets/images/guide/getting-started/visual-language/satoshi-symbols@2x.png
  guide/getting-started/visual-language.md
Labels: copy

#476 Added ⚡ content to `Getting Started` > `Hardware overview`
  assets/images/guide/getting-started/hardware/hardware-seed-storage-mobile.jpg
  assets/images/guide/getting-started/hardware/hardware-seed-storage-mobile@2x.jpg
  assets/images/guide/getting-started/hardware/hardware-seed-storage.jpg
  assets/images/guide/getting-started/hardware/hardware-seed-storage@2x.jpg
  assets/images/guide/getting-started/hardware/mining-hardware-mobile.jpg
  assets/images/guide/getting-started/hardware/mining-hardware-mobile@2x.jpg
  assets/images/guide/getting-started/hardware/mining-hardware.jpg
  assets/images/guide/getting-started/hardware/mining-hardware@2x.jpg
  guide/getting-started/hardware.md
Labels: copy

#480 Fixing broken links found via 'rake test'
  guide/designing-products/wallet-interoperability.md
  guide/getting-started/hardware.md
  guide/getting-started/software.md
  guide/getting-started/technology-primer.md
Labels: bug

#482 Added new image source file
  guide/getting-started/hardware.md
Labels: documentation

#490 Add ⚡️ content to `Designing Bitcoin Products` > `Design resources`
  guide/designing-products/design-resources.md
Labels: copy, Design Bitcoin Products

#488 Added ⚡️ content to `Designing Bitcoin Products` > `Why design for Bitcoin`
  guide/designing-products/why-design-for-bitcoin.md
Labels: copy, Design Bitcoin Products

#491 Added ⚡️ content to `Designing Bitcoin Products` > `Usage life cycle`
  guide/designing-products/usage-life-cycle.md
Labels: copy, Design Bitcoin Products

#496 Added BOLTs to glossary
  guide/glossary/index.md
Labels: copy
