Repository BitcoinDesign/Guide, pull requests merged in 2021-08, with the labels that each got.

#403 Added short summaries to the Resources page
  guide/designing-products/user-research-resources.md
Labels: copy

#447 Update node.md
  guide/glossary/node.md
Labels: copy

#448 Typo fix
  guide/glossary/node.md
Labels: copy

#451 Update Gemfile.lock
  Gemfile.lock
Labels: dev

#452 Cleaning up images in the coin selection page
  assets/images/guide/payments/coin-selection/funding-tx.jpg
  assets/images/guide/payments/coin-selection/funding-tx@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/blackjack.jpg
  assets/images/payments/coin-selection/automatic-algorithms/blackjack@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/bnb.jpg
  assets/images/payments/coin-selection/automatic-algorithms/bnb@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/fifo.jpg
  assets/images/payments/coin-selection/automatic-algorithms/fifo@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/high-priority-first.jpg
  assets/images/payments/coin-selection/automatic-algorithms/high-priority-first@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/lifo.jpg
  assets/images/payments/coin-selection/automatic-algorithms/lifo@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/minimise-fees-merge-coins.jpg
  assets/images/payments/coin-selection/automatic-algorithms/minimise-fees-merge-coins@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/minimise-fees-optimising-size.jpg
  assets/images/payments/coin-selection/automatic-algorithms/minimise-fees-optimising-size@2x.jpg
  assets/images/payments/coin-selection/automatic-algorithms/pruned-fifo.jpg
  assets/images/payments/coin-selection/automatic-algorithms/pruned-fifo@2x.jpg
  assets/images/payments/coin-selection/automatic-coin-selection-mobile.jpg
  assets/images/payments/coin-selection/automatic-coin-selection-mobile@2x.jpg
  assets/images/payments/coin-selection/automatic-coin-selection.jpg
  assets/images/payments/coin-selection/automatic-coin-selection@2x.jpg
  assets/images/payments/coin-selection/coin-selection-header-mobile.jpg
  assets/images/payments/coin-selection/coin-selection-header-mobile@2x.jpg
  assets/images/payments/coin-selection/coin-selection-header.jpg
  assets/images/payments/coin-selection/coin-selection-header@2x.jpg
  assets/images/payments/coin-selection/coin-selection-white-black-listing-mobile.jpg
  assets/images/payments/coin-selection/coin-selection-white-black-listing-mobile@2x.jpg
  assets/images/payments/coin-selection/coin-selection-white-black-listing.jpg
  assets/images/payments/coin-selection/coin-selection-white-black-listing@2x.jpg
  assets/images/payments/coin-selection/funding-tx-mobile.jpg
  assets/images/payments/coin-selection/funding-tx-mobile@2x.jpg
  assets/images/payments/coin-selection/funding-tx.jpg
  assets/images/payments/coin-selection/funding-tx@2x.jpg
  assets/images/payments/coin-selection/manual-coin-selection-mobile.jpg
  assets/images/payments/coin-selection/manual-coin-selection-mobile@2x.jpg
  assets/images/payments/coin-selection/manual-coin-selection.jpg
  assets/images/payments/coin-selection/manual-coin-selection@2x.jpg
Labels: bug, design

#438 Update hardware.md
  guide/getting-started/hardware.md
Labels: copy

#441 Tidied up examples in 'Automatic coin selection' in coin-selection.md
  guide/payments/coin-selection.md
Labels: enhancement, payments

#458 Updated fee image in 'payments/send'
  assets/images/guide/payments/send/select-fee-rate.png
  assets/images/guide/payments/send/select-fee-rate@2x.png
  guide/payments/send.md
Labels: design

#453 Fix for #190 - created artwork for Principles page
  _compress_images_cache.yml
  _sass/minima/_article.scss
  _sass/minima/_principles-page.scss
  _sass/minima/initialize.scss
  assets/images/guide/designing-products/principles/page-principles.jpg
  assets/images/guide/designing-products/principles/principle-decentralization.png
  assets/images/guide/designing-products/principles/principle-decentralization@2x.png
  assets/images/guide/designing-products/principles/principle-inclusion.png
  assets/images/guide/designing-products/principles/principle-inclusion@2x.png
  assets/images/guide/designing-products/principles/principle-interoperability.png
  assets/images/guide/designing-products/principles/principle-interoperability@2x.png
  assets/images/guide/designing-products/principles/principle-privacy.png
  assets/images/guide/designing-products/principles/principle-privacy@2x.png
  assets/images/guide/designing-products/principles/principle-security.png
  assets/images/guide/designing-products/principles/principle-security@2x.png
  assets/images/guide/designing-products/principles/principle-self-custody.png
  assets/images/guide/designing-products/principles/principle-self-custody@2x.png
  assets/images/guide/designing-products/principles/principle-transparency.png
  assets/images/guide/designing-products/principles/principle-transparency@2x.png
  assets/images/guide/designing-products/principles/principles-mobile.jpg
  assets/images/guide/designing-products/principles/principles-mobile.png
  assets/images/guide/designing-products/principles/principles-mobile@2x.jpg
  assets/images/guide/designing-products/principles/principles-mobile@2x.png
  assets/images/guide/designing-products/principles/principles-preview.png
  assets/images/guide/designing-products/principles/principles.jpg
  assets/images/guide/designing-products/principles/principles.png
  assets/images/guide/designing-products/principles/principles@2x.jpg
  assets/images/guide/designing-products/principles/principles@2x.png
  guide/designing-products/principles.md
Labels: design

#459 Removing footnotes on the coin selection page
  guide/payments/coin-selection.md
Labels: copy
