Repository BitcoinDesign/Guide, pull requests merged in 2021-07, with the labels that each got.

#412 Add latest FCA research to the user research references page
  guide/designing-products/user-research-resources.md
Labels: copy

#419 Add UI kit to the projects page
  assets/images/contribute/bitcoin-ui-kit.svg
  projects.md
Labels: copy

#413 Added design resources page
  _compress_images_cache.yml
  _sass/minima/_design-resources-page.scss
  _sass/minima/initialize.scss
  assets/images/guide/designing-products/design-resources/art-meets-bitcoin.jpg
  assets/images/guide/designing-products/design-resources/art-meets-bitcoin@2x.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-design-site.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-design-site@2x.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-hardware-illustrations.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-hardware-illustrations@2x.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-icons.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-icons@2x.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-ui-kit.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-ui-kit@2x.jpg
  assets/images/guide/designing-products/design-resources/design-resources-preview.jpg
  assets/images/guide/designing-products/design-resources/slide-template.jpg
  assets/images/guide/designing-products/design-resources/slide-template@2x.jpg
  guide/designing-products/design-resources.md
  guide/designing-products/designing-products.md
  guide/designing-products/wallet-interoperability.md
Labels: copy, design

#411 Adds glossary sub-page for nodes
  _compress_images_cache.yml
  assets/images/guide/glossary/node/archival-node.png
  assets/images/guide/glossary/node/archival-node@2x.png
  assets/images/guide/glossary/node/bloom-filter-node.png
  assets/images/guide/glossary/node/bloom-filter-node@2x.png
  assets/images/guide/glossary/node/hardware-node.png
  assets/images/guide/glossary/node/hardware-node@2x.png
  assets/images/guide/glossary/node/local-node.png
  assets/images/guide/glossary/node/local-node@2x.png
  assets/images/guide/glossary/node/multiple-third-party-nodes.png
  assets/images/guide/glossary/node/multiple-third-party-nodes@2x.png
  assets/images/guide/glossary/node/node-mobile.jpg
  assets/images/guide/glossary/node/node-mobile@2x.jpg
  assets/images/guide/glossary/node/node-preview.jpg
  assets/images/guide/glossary/node/node.jpg
  assets/images/guide/glossary/node/node@2x.jpg
  assets/images/guide/glossary/node/own-hosted-node.png
  assets/images/guide/glossary/node/own-hosted-node@2x.png
  assets/images/guide/glossary/node/pruned-node.png
  assets/images/guide/glossary/node/pruned-node@2x.png
  assets/images/guide/glossary/node/spv-node.png
  assets/images/guide/glossary/node/spv-node@2x.png
  assets/images/guide/glossary/node/third-party-api.png
  assets/images/guide/glossary/node/third-party-api@2x.png
  assets/images/guide/glossary/node/third-party-node.png
  assets/images/guide/glossary/node/third-party-node@2x.png
  guide/glossary/index.md
  guide/glossary/node.md
  guide/glossary/wallet.md
Labels: copy

#425 Case studies - Add illustration sources
  guide/case-studies/cloud-backup.md
  guide/case-studies/introduction.md
  guide/case-studies/savings-account.md
  guide/case-studies/shared-account.md
  guide/case-studies/upgradeable-wallet.md
Labels: documentation

#431 Updated YouTube channel URL
  _config.yml
Labels: copy

#422 New next and previous buttons
  _includes/next-previous.html
  _sass/minima/_next-previous.scss
  _sass/minima/initialize.scss
  guide.md
  guide/case-studies/cloud-backup.md
  guide/case-studies/introduction.md
  guide/case-studies/savings-account.md
  guide/case-studies/shared-account.md
  guide/case-studies/upgradeable-wallet.md
  guide/contribute/content-guidelines.md
  guide/contribute/contribute.md
  guide/contribute/formatting.md
  guide/contribute/illustration-guidelines.md
  guide/contribute/propose-a-change.md
  guide/contribute/review.md
  guide/designing-products/common-user-flows.md
  guide/designing-products/design-resources.md
  guide/designing-products/designing-products.md
  guide/designing-products/open-design.md
  guide/designing-products/personal-finance.md
  guide/designing-products/principles.md
  guide/designing-products/usage-life-cycle.md
  guide/designing-products/user-research-resources.md
  guide/designing-products/user-research.md
  guide/designing-products/wallet-interoperability.md
  guide/designing-products/why-design-for-bitcoin.md
  guide/getting-started/getting-started.md
  guide/getting-started/hardware.md
  guide/getting-started/software.md
  guide/getting-started/technology-primer.md
  guide/getting-started/visual-language.md
  guide/getting-started/why-bitcoin-is-unique.md
  guide/onboarding/automatic-cloud-backup.md
  guide/onboarding/backing-up-a-recovery-phrase.md
  guide/onboarding/creating-a-new-wallet.md
  guide/onboarding/funding-a-wallet.md
  guide/onboarding/getting-to-know-your-users.md
  guide/onboarding/introduction.md
  guide/onboarding/manual-backup.md
  guide/onboarding/protecting-a-wallet.md
  guide/onboarding/restoring-a-wallet.md
  guide/payments/introduction.md
  guide/payments/privacy.md
  guide/payments/receive.md
  guide/payments/send.md
  guide/payments/transactions.md
  guide/private-key-management/backups.md
  guide/private-key-management/cloud-backup.md
  guide/private-key-management/external-signing-device.md
  guide/private-key-management/introduction.md
  guide/private-key-management/manual-backup.md
  guide/private-key-management/multi-key.md
  guide/private-key-management/overview.md
Labels: copy, dev

#427 Link fixes found via rake test
  guide/glossary/index.md
  guide/onboarding/creating-a-new-wallet.md
  guide/payments/privacy.md
  guide/private-key-management/cloud-backup.md
  guide/private-key-management/manual-backup.md
Labels: bug

#426 Update multi-key.md
  guide/private-key-management/multi-key.md
Labels: copy

#434 Re-added preview image for the savings account case study page
  assets/images/guide/case-studies/multisig-wallet/multisig-wallet-preview.jpg
Labels: design
