Repository BitcoinDesign/Guide, pull requests merged in 2022-08, with the labels that each got.

#883 Lightning services broken link fix
  guide/how-it-works/lightning-services.md
Labels: Bug

#876 Add balances to activity screens
  _compress_images_cache.yml
  assets/images/guide/daily-spending-wallet/activity/activity-big.png
  assets/images/guide/daily-spending-wallet/activity/activity-ids-big.png
  assets/images/guide/daily-spending-wallet/activity/activity-ids.png
  assets/images/guide/daily-spending-wallet/activity/activity-ids@2x.png
  assets/images/guide/daily-spending-wallet/activity/activity.png
  assets/images/guide/daily-spending-wallet/activity/activity@2x.png
  assets/images/guide/daily-spending-wallet/activity/annotated-activity-big.png
  assets/images/guide/daily-spending-wallet/activity/annotated-activity.png
  assets/images/guide/daily-spending-wallet/activity/annotated-activity@2x.png
  assets/images/guide/daily-spending-wallet/activity/budgeting-big.png
  assets/images/guide/daily-spending-wallet/activity/budgeting.png
  assets/images/guide/daily-spending-wallet/activity/budgeting@2x.png
  assets/images/guide/daily-spending-wallet/activity/expanded-micropayments-big.png
  assets/images/guide/daily-spending-wallet/activity/expanded-micropayments.png
  assets/images/guide/daily-spending-wallet/activity/expanded-micropayments@2x.png
  assets/images/guide/daily-spending-wallet/activity/grouped-micropayments-big.png
  assets/images/guide/daily-spending-wallet/activity/grouped-micropayments.png
  assets/images/guide/daily-spending-wallet/activity/grouped-micropayments@2x.png
  assets/images/guide/daily-spending-wallet/activity/invoice-big.png
  assets/images/guide/daily-spending-wallet/activity/invoice.png
  assets/images/guide/daily-spending-wallet/activity/invoice@2x.png
  assets/images/guide/daily-spending-wallet/activity/micropayments-big.png
  assets/images/guide/daily-spending-wallet/activity/micropayments.png
  assets/images/guide/daily-spending-wallet/activity/micropayments@2x.png
  assets/images/guide/daily-spending-wallet/activity/non-payment-activity-big.png
  assets/images/guide/daily-spending-wallet/activity/non-payment-activity.png
  assets/images/guide/daily-spending-wallet/activity/non-payment-activity@2x.png
  assets/images/guide/daily-spending-wallet/activity/search-big.png
  assets/images/guide/daily-spending-wallet/activity/search.png
  assets/images/guide/daily-spending-wallet/activity/search@2x.png
  assets/images/guide/daily-spending-wallet/activity/semi-annotated-activity-big.png
  assets/images/guide/daily-spending-wallet/activity/semi-annotated-activity.png
  assets/images/guide/daily-spending-wallet/activity/semi-annotated-activity@2x.png
  assets/images/guide/daily-spending-wallet/activity/sending-big.png
  assets/images/guide/daily-spending-wallet/activity/sending.png
  assets/images/guide/daily-spending-wallet/activity/sending@2x.png
  assets/images/guide/daily-spending-wallet/activity/status-field.png
  assets/images/guide/daily-spending-wallet/activity/status-field@2x.png
  assets/images/guide/daily-spending-wallet/activity/tips-big.png
  assets/images/guide/daily-spending-wallet/activity/tips.png
  assets/images/guide/daily-spending-wallet/activity/tips@2x.png
  guide/daily-spending-wallet/activity.md
Labels: Design, Daily spending wallet

#872 Security page revision
  _compress_images_cache.yml
  assets/images/guide/daily-spending-wallet/security/checklist-option-details-big.png
  assets/images/guide/daily-spending-wallet/security/checklist-option-details.png
  assets/images/guide/daily-spending-wallet/security/checklist-option-details@2x.png
  assets/images/guide/daily-spending-wallet/security/choose-fake-wallet-pin-big.png
  assets/images/guide/daily-spending-wallet/security/choose-fake-wallet-pin.png
  assets/images/guide/daily-spending-wallet/security/choose-fake-wallet-pin@2x.png
  assets/images/guide/daily-spending-wallet/security/choose-pin-big.png
  assets/images/guide/daily-spending-wallet/security/choose-pin.png
  assets/images/guide/daily-spending-wallet/security/choose-pin@2x.png
  assets/images/guide/daily-spending-wallet/security/delete-recovery-phrase-big.png
  assets/images/guide/daily-spending-wallet/security/delete-recovery-phrase.png
  assets/images/guide/daily-spending-wallet/security/delete-recovery-phrase@2x.png
  assets/images/guide/daily-spending-wallet/security/delete-wallet-big.png
  assets/images/guide/daily-spending-wallet/security/delete-wallet.png
  assets/images/guide/daily-spending-wallet/security/delete-wallet@2x.png
  assets/images/guide/daily-spending-wallet/security/enter-pin-big.png
  assets/images/guide/daily-spending-wallet/security/enter-pin-scrambled-big.png
  assets/images/guide/daily-spending-wallet/security/enter-pin-scrambled.png
  assets/images/guide/daily-spending-wallet/security/enter-pin-scrambled@2x.png
  assets/images/guide/daily-spending-wallet/security/enter-pin.png
  assets/images/guide/daily-spending-wallet/security/enter-pin@2x.png
  assets/images/guide/daily-spending-wallet/security/face-id-info-big.png
  assets/images/guide/daily-spending-wallet/security/face-id-info.png
  assets/images/guide/daily-spending-wallet/security/face-id-info@2x.png
  assets/images/guide/daily-spending-wallet/security/home-security-reminder-big.png
  assets/images/guide/daily-spending-wallet/security/home-security-reminder.png
  assets/images/guide/daily-spending-wallet/security/home-security-reminder@2x.png
  assets/images/guide/daily-spending-wallet/security/inadequate-security-big.png
  assets/images/guide/daily-spending-wallet/security/inadequate-security.png
  assets/images/guide/daily-spending-wallet/security/inadequate-security@2x.png
  assets/images/guide/daily-spending-wallet/security/lightning-network-settings-big.png
  assets/images/guide/daily-spending-wallet/security/lightning-network-settings.png
  assets/images/guide/daily-spending-wallet/security/lightning-network-settings@2x.png
  assets/images/guide/daily-spending-wallet/security/privacy-and-security-settings-big.png
  assets/images/guide/daily-spending-wallet/security/privacy-and-security-settings.png
  assets/images/guide/daily-spending-wallet/security/privacy-and-security-settings@2x.png
  assets/images/guide/daily-spending-wallet/security/privacy-checklist-big.png
  assets/images/guide/daily-spending-wallet/security/privacy-checklist.png
  assets/images/guide/daily-spending-wallet/security/privacy-checklist@2x.png
  assets/images/guide/daily-spending-wallet/security/security-checklist-big.png
  assets/images/guide/daily-spending-wallet/security/security-checklist.png
  assets/images/guide/daily-spending-wallet/security/security-checklist@2x.png
  assets/images/guide/daily-spending-wallet/security/security-reminder-modal-big.png
  assets/images/guide/daily-spending-wallet/security/security-reminder-modal.png
  assets/images/guide/daily-spending-wallet/security/security-reminder-modal@2x.png
  assets/images/guide/daily-spending-wallet/security/wallet-limit-reached-big.png
  assets/images/guide/daily-spending-wallet/security/wallet-limit-reached.png
  assets/images/guide/daily-spending-wallet/security/wallet-limit-reached@2x.png
  assets/images/guide/daily-spending-wallet/security/watchtower-details-big.png
  assets/images/guide/daily-spending-wallet/security/watchtower-details-custom-big.png
  assets/images/guide/daily-spending-wallet/security/watchtower-details-custom.png
  assets/images/guide/daily-spending-wallet/security/watchtower-details-custom@2x.png
  assets/images/guide/daily-spending-wallet/security/watchtower-details.png
  assets/images/guide/daily-spending-wallet/security/watchtower-details@2x.png
  guide/daily-spending-wallet/security.md
Labels: Copy, Design, Daily spending wallet

#873 Add Design Stickers Figma File to Design Files
  _compress_images_cache.yml
  assets/images/guide/resources/design-files/bitcoin-design-stickers.jpg
  assets/images/guide/resources/design-files/bitcoin-design-stickers@2x.jpg
  guide/resources/design-files.md
Labels: Copy

#880 Adding various YouTube video references
  _compress_images_cache.yml
  assets/images/guide/designing-products/accessibility/learning-bitcoin-and-design-accessibility.jpg
  assets/images/guide/designing-products/accessibility/learning-bitcoin-and-design-accessibility@2x.jpg
  assets/images/guide/designing-products/user-research/ux-research-call-1-user-personas.jpg
  assets/images/guide/designing-products/user-research/ux-research-call-1-user-personas@2x.jpg
  assets/images/guide/designing-products/user-research/ux-research-call-2-user-stories.jpg
  assets/images/guide/designing-products/user-research/ux-research-call-2-user-stories@2x.jpg
  assets/images/guide/getting-started/open-design/learning-bitcoin-and-design-open-design.jpg
  assets/images/guide/getting-started/open-design/learning-bitcoin-and-design-open-design@2x.jpg
  assets/images/guide/getting-started/open-design/supporting-open-design-fosdem.jpg
  assets/images/guide/getting-started/open-design/supporting-open-design-fosdem@2x.jpg
  assets/images/guide/getting-started/technology/learning-bitcoin-and-design-lightning-primer.jpg
  assets/images/guide/getting-started/technology/learning-bitcoin-and-design-lightning-primer@2x.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/bitcoin-is-for-everyone-hello-bitcoin.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/bitcoin-is-for-everyone-hello-bitcoin@2x.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/what-is-bitcoin-and-why-does-it-matter.jpg
  assets/images/guide/getting-started/why-bitcoin-is-unique/what-is-bitcoin-and-why-does-it-matter@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/learning-bitcoin-and-design-bolt12.jpg
  assets/images/guide/how-it-works/payment-request-formats/learning-bitcoin-and-design-bolt12@2x.jpg
  guide/designing-products/accessibility.md
  guide/designing-products/user-research.md
  guide/getting-started/open-design.md
  guide/getting-started/technology-primer.md
  guide/getting-started/why-bitcoin-is-unique.md
  guide/how-it-works/payment-request-formats.md
Labels: Documentation

#894 Fix for inline image code snippet
  guide/contribute/formatting/media.md
Labels: Bug

#893 Minor fixes to Units and symbols, Getting to know your users and Design research
  guide/designing-products/getting-to-know-your-users.md
  guide/resources/design-research.md
  js/scripts.js
Labels: Copy

#898 New settings page for the daily spending wallet
  _compress_images_cache.yml
  assets/images/guide/daily-spending-wallet/settings/advanced-big.png
  assets/images/guide/daily-spending-wallet/settings/advanced.png
  assets/images/guide/daily-spending-wallet/settings/advanced@2x.png
  assets/images/guide/daily-spending-wallet/settings/bitcoin-network-big.png
  assets/images/guide/daily-spending-wallet/settings/bitcoin-network.png
  assets/images/guide/daily-spending-wallet/settings/bitcoin-network@2x.png
  assets/images/guide/daily-spending-wallet/settings/bitcoin-unit-big.png
  assets/images/guide/daily-spending-wallet/settings/bitcoin-unit.png
  assets/images/guide/daily-spending-wallet/settings/bitcoin-unit@2x.png
  assets/images/guide/daily-spending-wallet/settings/delete-wallet-big.png
  assets/images/guide/daily-spending-wallet/settings/delete-wallet.png
  assets/images/guide/daily-spending-wallet/settings/delete-wallet@2x.png
  assets/images/guide/daily-spending-wallet/settings/fees-big.png
  assets/images/guide/daily-spending-wallet/settings/fees.png
  assets/images/guide/daily-spending-wallet/settings/fees@2x.png
  assets/images/guide/daily-spending-wallet/settings/general-big.png
  assets/images/guide/daily-spending-wallet/settings/general.png
  assets/images/guide/daily-spending-wallet/settings/general@2x.png
  assets/images/guide/daily-spending-wallet/settings/help-big.png
  assets/images/guide/daily-spending-wallet/settings/help.png
  assets/images/guide/daily-spending-wallet/settings/help@2x.png
  assets/images/guide/daily-spending-wallet/settings/lightning-network-big.png
  assets/images/guide/daily-spending-wallet/settings/lightning-network.png
  assets/images/guide/daily-spending-wallet/settings/lightning-network@2x.png
  assets/images/guide/daily-spending-wallet/settings/local-currency-big.png
  assets/images/guide/daily-spending-wallet/settings/local-currency.png
  assets/images/guide/daily-spending-wallet/settings/local-currency@2x.png
  assets/images/guide/daily-spending-wallet/settings/network-big.png
  assets/images/guide/daily-spending-wallet/settings/network.png
  assets/images/guide/daily-spending-wallet/settings/network@2x.png
  assets/images/guide/daily-spending-wallet/settings/overview-big.png
  assets/images/guide/daily-spending-wallet/settings/overview.png
  assets/images/guide/daily-spending-wallet/settings/overview@2x.png
  assets/images/guide/daily-spending-wallet/settings/privacy-big.png
  assets/images/guide/daily-spending-wallet/settings/privacy.png
  assets/images/guide/daily-spending-wallet/settings/privacy@2x.png
  assets/images/guide/daily-spending-wallet/settings/security-big.png
  assets/images/guide/daily-spending-wallet/settings/security.png
  assets/images/guide/daily-spending-wallet/settings/security@2x.png
  assets/images/guide/daily-spending-wallet/settings/settings-mobile.jpg
  assets/images/guide/daily-spending-wallet/settings/settings-mobile@2x.jpg
  assets/images/guide/daily-spending-wallet/settings/settings-preview.jpg
  assets/images/guide/daily-spending-wallet/settings/settings.jpg
  assets/images/guide/daily-spending-wallet/settings/settings@2x.jpg
  assets/images/guide/daily-spending-wallet/settings/wallet-backup-big.png
  assets/images/guide/daily-spending-wallet/settings/wallet-backup.png
  assets/images/guide/daily-spending-wallet/settings/wallet-backup@2x.png
  assets/images/guide/daily-spending-wallet/settings/watchtower-big.png
  assets/images/guide/daily-spending-wallet/settings/watchtower.png
  assets/images/guide/daily-spending-wallet/settings/watchtower@2x.png
  guide/daily-spending-wallet/privacy.md
  guide/daily-spending-wallet/settings.md
Labels: Copy, Design, Daily spending wallet

#885 Sign in with bitcoin page
  _compress_images_cache.yml
  assets/images/guide/how-it-works/sign-in-with-bitcoin/bridged-connection.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/bridged-connection@2x.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/bridged-payment-request.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/bridged-payment-request@2x.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/connected-wallets.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/connected-wallets@2x.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/direct-connection.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/direct-connection@2x.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/payment-request.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/payment-request@2x.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin-mobile-1.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin-mobile.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin-mobile@2x-1.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin-mobile@2x.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin-preview.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/sign-in-with-bitcoin@2x.jpg
  assets/images/guide/how-it-works/sign-in-with-bitcoin/signin-info.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/signin-info@2x.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/signin-request.png
  assets/images/guide/how-it-works/sign-in-with-bitcoin/signin-request@2x.png
  guide/contribute/contribute.md
  guide/daily-spending-wallet/activity.md
  guide/glossary/index.md
  guide/how-it-works/introduction.md
  guide/how-it-works/sign-in-with-bitcoin.md
  guide/how-it-works/transactions.md
  guide/resources/introduction.md
  guide/shared-wallet.md
Labels: Copy, Design

#900 Add links to new mnemonics research
  guide/designing-products/accessibility.md
  guide/how-it-works/private-key-management/manual-backup.md
  guide/resources/design-research.md
Labels: Copy

#899 Adds a "Feedback & questions" button to guide pages
  _includes/next-previous.html
  _sass/minima/_next-previous.scss
  js/scripts.js
Labels: Dev
