Repository BitcoinDesign/Guide, pull requests merged in 2022-04, with the labels that each got.

#743 Updated image request template to add some tips
  .github/ISSUE_TEMPLATE/---image-request.md
Labels: Documentation

#727 🎨 [Guide Re-org] - Guide landing page revision
  _compress_images_cache.yml
  _sass/minima/_guide-page.scss
  _sass/minima/initialize.scss
  assets/images/guide/bitcoin-island.jpg
  assets/images/guide/bitcoin-island@2x.jpg
  assets/images/guide/daily-spending-mobile.png
  assets/images/guide/daily-spending-mobile@2x.png
  assets/images/guide/daily-spending.png
  assets/images/guide/daily-spending@2x.png
  assets/images/guide/designing-bitcoin-products.png
  assets/images/guide/designing-bitcoin-products@2x.png
  assets/images/guide/getting-started.png
  assets/images/guide/getting-started@2x.png
  assets/images/guide/savings-account.png
  assets/images/guide/savings-account@2x.png
  assets/images/guide/shared-accounts.png
  assets/images/guide/shared-accounts@2x.png
  assets/images/guide/upgradeable-account.png
  assets/images/guide/upgradeable-account@2x.png
  guide.md
Labels: Copy, Design

#568 Add `Lightning service providers` page to `How it works` section
  _compress_images_cache.yml
  assets/images/guide/how-it-works/lightning-service-providers/backups-recovery.jpg
  assets/images/guide/how-it-works/lightning-service-providers/backups-recovery@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/channel-opens.jpg
  assets/images/guide/how-it-works/lightning-service-providers/channel-opens@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/dual-funding.jpg
  assets/images/guide/how-it-works/lightning-service-providers/dual-funding@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/inbound-liquidity.jpg
  assets/images/guide/how-it-works/lightning-service-providers/inbound-liquidity@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-address.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-address@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-service-providers-mobile.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-service-providers-mobile@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-service-providers-preview.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-service-providers.jpg
  assets/images/guide/how-it-works/lightning-service-providers/lightning-service-providers@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/payment-forwarding.jpg
  assets/images/guide/how-it-works/lightning-service-providers/payment-forwarding@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/spend-unconfirmed.jpg
  assets/images/guide/how-it-works/lightning-service-providers/spend-unconfirmed@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/swap-in.jpg
  assets/images/guide/how-it-works/lightning-service-providers/swap-in@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/swap-out.jpg
  assets/images/guide/how-it-works/lightning-service-providers/swap-out@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/watchtowers.jpg
  assets/images/guide/how-it-works/lightning-service-providers/watchtowers@2x.jpg
  assets/images/guide/how-it-works/lightning-service-providers/zero-reserve.jpg
  assets/images/guide/how-it-works/lightning-service-providers/zero-reserve@2x.jpg
  guide/daily-spending-wallet/first-use.md
  guide/designing-products/personal-finance.md
  guide/designing-products/wallet-interoperability.md
  guide/how-it-works/coin-selection.md
  guide/how-it-works/introduction.md
  guide/how-it-works/lightning-service-providers.md
  guide/how-it-works/node.md
Labels: Copy, Design Bitcoin Products

#749 Added the BlockFi survey to the design research page
  guide/resources/design-research.md
Labels: Copy

#747 Moved remaining case studies to top-level as reference designs
  assets/images/guide/case-studies/case-studies-mobile.jpg
  assets/images/guide/case-studies/case-studies-mobile@2x.jpg
  assets/images/guide/case-studies/case-studies.jpg
  assets/images/guide/case-studies/case-studies@2x.jpg
  assets/images/guide/case-studies/page-case-studies.jpg
  guide.md
  guide/case-studies/introduction.md
  guide/contribute/contribute.md
  guide/daily-spending-wallet/privacy.md
  guide/designing-products/getting-to-know-your-users.md
  guide/designing-products/personal-finance.md
  guide/glossary/index.md
  guide/how-it-works/introduction.md
  guide/how-it-works/private-key-management/multi-key.md
  guide/how-it-works/transactions.md
  guide/resources/introduction.md
  guide/savings-wallet.md
  guide/shared-account.md
  guide/upgradeable-wallet.md
Labels: Copy

#748 Cleaned up compress image file
  _compress_images_cache.yml
Labels: Dev

#751 Adds Jekyll filter to prevents runts for image captions
  _includes/image.html
  _includes/picture.html
  _plugins/no_runts.rb
Labels: Dev

#757 Renaming case study to reference design in a few remaining places
  guide/daily-spending-wallet/privacy.md
  guide/designing-products/personal-finance.md
  guide/how-it-works/private-key-management/multi-key.md
  guide/savings-wallet.md
  guide/shared-account.md
Labels: Copy

#752 Adds a "Reference designs" category header to the sidebar
  _includes/secondary-nav.html
  _sass/minima/_nav-list.scss
  _sass/minima/_site-header.scss
  guide/daily-spending-wallet/landing-page.md
  guide/shared-account.md
Labels: Design

#755 Minor grammar fixes
  guide/how-it-works/backups.md
  guide/how-it-works/coin-selection.md
  guide/how-it-works/introduction.md
  guide/how-it-works/lightning-service-providers.md
  guide/how-it-works/node.md
  guide/how-it-works/payment-request-formats.md
  guide/how-it-works/transactions.md
Labels: Copy

#765 Add info about Child-pays-for-parent to the glossary
  guide/glossary/index.md
Labels: Copy

#769 Add link to roadmap and issues to Contribute page
  guide/contribute/contribute.md
Labels: Copy, Contribute

#772 Minor fix to the no runts plugin
  _plugins/no_runts.rb
Labels: Bug, Dev

#764 Add info about the gap limit to the glossary
  guide/glossary/index.md
Labels: Copy

#761 Clean up `Interoperability` page.
  _compress_images_cache.yml
  assets/images/guide/designing-products/interoperability/hardware-wallets.jpg
  assets/images/guide/designing-products/interoperability/hardware-wallets@2x.jpg
  assets/images/guide/designing-products/interoperability/integrations.jpg
  assets/images/guide/designing-products/interoperability/integrations@2x.jpg
  assets/images/guide/designing-products/interoperability/key-import-export.jpg
  assets/images/guide/designing-products/interoperability/key-import-export@2x.jpg
  assets/images/guide/designing-products/interoperability/multi-signature.jpg
  assets/images/guide/designing-products/interoperability/multi-signature@2x.jpg
  assets/images/guide/designing-products/interoperability/node-options.jpg
  assets/images/guide/designing-products/interoperability/node-options@2x.jpg
  assets/images/guide/designing-products/interoperability/payment-links.jpg
  assets/images/guide/designing-products/interoperability/payment-links@2x.jpg
  assets/images/guide/designing-products/interoperability/qr-code.jpg
  assets/images/guide/designing-products/interoperability/qr-code@2x.jpg
  assets/images/guide/designing-products/interoperability/transaction-file.jpg
  assets/images/guide/designing-products/interoperability/transaction-file@2x.jpg
  assets/images/guide/designing-products/interoperability/user-data-import-export.jpg
  assets/images/guide/designing-products/interoperability/user-data-import-export@2x.jpg
  assets/images/guide/designing-products/interoperability/user-interface.jpg
  assets/images/guide/designing-products/interoperability/user-interface@2x.jpg
  assets/images/guide/designing-products/interoperability/wallet-interoperability-mobile.jpg
  assets/images/guide/designing-products/interoperability/wallet-interoperability-mobile@2x.jpg
  assets/images/guide/designing-products/interoperability/wallet-interoperability-preview.jpg
  assets/images/guide/designing-products/interoperability/wallet-interoperability.jpg
  assets/images/guide/designing-products/interoperability/wallet-interoperability@2x.jpg
  guide/daily-spending-wallet/backup-and-recovery/recovery.md
  guide/daily-spending-wallet/landing-page.md
  guide/daily-spending-wallet/requesting.md
  guide/daily-spending-wallet/sending.md
  guide/designing-products/common-user-flows.md
  guide/designing-products/designing-products.md
  guide/designing-products/interoperability.md
  guide/designing-products/units-and-symbols.md
  guide/getting-started/principles.md
  guide/glossary/index.md
  guide/how-it-works/lightning-service-providers.md
Labels: Copy

#753 Added note around localization considerations for recovery phrases in the glossary
  guide/daily-spending-wallet/backup-and-recovery/recovery.md
  guide/glossary/index.md
  guide/how-it-works/private-key-management/manual-backup.md
Labels: Copy

#773 Added POS to `Hardware categories` page
  _compress_images_cache.yml
  assets/images/guide/getting-started/hardware/point-of-sale-mobile.jpg
  assets/images/guide/getting-started/hardware/point-of-sale-mobile@2x.jpg
  assets/images/guide/getting-started/hardware/point-of-sale.jpg
  assets/images/guide/getting-started/hardware/point-of-sale@2x.jpg
  guide/getting-started/hardware.md
Labels: Copy, Design, Getting started

#795 Update design-research.md
  guide/resources/design-research.md
Labels: Copy
