Repository BitcoinDesign/Guide, pull requests merged in 2022-01, with the labels that each got.

#588 Added content Designing Bitcoin Products > Open Design (Issue #484)
  guide/designing-products/open-design.md
Labels: copy, Design Bitcoin Products

#614 Deep-link scroll fix
  _sass/minima/_layout.scss
Labels: bug

#613 Adds a new /calendar page
  _compress_images_cache.yml
  _includes/emoji-box.html
  _sass/minima/_mixins.scss
  _sass/minima/_site-footer.scss
  _sass/minima/article/_emoji-box.scss
  _sass/minima/initialize.scss
  assets/images/calendar/calendar-mobile.png
  assets/images/calendar/calendar-mobile@2x.png
  assets/images/calendar/calendar.png
  assets/images/calendar/calendar@2x.png
  calendar.md
  contribute.md
  projects.md
Labels: dev, copy, design

#621 Minor calendar page revision
  _compress_images_cache.yml
  assets/images/calendar/calendar-preview.jpg
  calendar.md
Labels: copy

#609 Proposal for bitcoin header theme banner
  _compress_images_cache.yml
  assets/images/home/banner/rutuja_bitcoin_theme_banner_web.jpg
  assets/images/home/banner/rutuja_bitcoin_theme_banner_web@2x.jpg
  assets/images/home/banner/themeBG_mobile.jpg
  assets/images/home/banner/themeBG_mobile@2x.jpg
  js/themes.js
Labels: design

#623 Minor copy addition
  guide/getting-started/why-bitcoin-is-unique.md
Labels: copy

#624 Minor tweaks to the "Backing up a wallet" page
  guide/onboarding/backing-up-a-wallet.md
Labels: copy
