Repository BitcoinDesign/Guide, pull requests merged in 2022-03, with the labels that each got.

#680 Add offline error to the send page
  _compress_images_cache.yml
  assets/images/guide/payments/send/offline-error.png
  assets/images/guide/payments/send/offline-error@2x.png
  guide/payments/send.md
Labels: Copy, Design, Lightning

#651 Updated `Payments` > `Requesting` page
  _compress_images_cache.yml
  assets/images/guide/payments/request/Home@2x.png
  assets/images/guide/payments/request/contactless.png
  assets/images/guide/payments/request/contactless@2x.png
  assets/images/guide/payments/request/home.png
  assets/images/guide/payments/request/node-id.png
  assets/images/guide/payments/request/node-id@2x.png
  assets/images/guide/payments/request/plaintext-single-use.png
  assets/images/guide/payments/request/plaintext-single-use@2x.png
  assets/images/guide/payments/request/single-use-address-type.png
  assets/images/guide/payments/request/single-use-address-type@2x.png
  assets/images/guide/payments/request/single-use-invoice-settings.png
  assets/images/guide/payments/request/single-use-payment-request-settings-address.png
  assets/images/guide/payments/request/single-use-payment-request-settings-address@2x.png
  assets/images/guide/payments/request/single-use-payment-request-settings.png
  assets/images/guide/payments/request/single-use-payment-request-settings@2x.png
  assets/images/guide/payments/request/single-use-payment-request.png
  assets/images/guide/payments/request/single-use-payment-request@2x.png
  assets/images/guide/payments/request/single-use-transaction-request-settings.png
  assets/images/guide/payments/request/single-use-transaction-request-settings@2x.png
  assets/images/guide/payments/request/single-use-transaction-request.png
  assets/images/guide/payments/request/single-use-transaction-request@2x.png
  assets/images/guide/payments/request/withdraw-request.png
  assets/images/guide/payments/request/withdraw-request@2x.png
  guide/glossary/index.md
  guide/payments/request.md
Labels: Payments, Copy

#697 Added info about contact cards for wallet owners
  _compress_images_cache.yml
  assets/images/guide/payments/contacts/owner-entry.png
  assets/images/guide/payments/contacts/owner-entry@2x.png
  assets/images/guide/payments/contacts/owner-list.png
  assets/images/guide/payments/contacts/owner-list@2x.png
  guide/payments/contacts.md
Labels: Copy, Design

#676 Banner Image for Payment Request Page
  _compress_images_cache.yml
  assets/images/guide/payments/request/request-banner(1600x600).png
  assets/images/guide/payments/request/request-banner(3200x1200).png
  assets/images/guide/payments/request/request-banner(400x200).png
  assets/images/guide/payments/request/request-banner(800x400).png
  assets/images/guide/payments/request/request-banner-preview(1200x630).png
  guide/payments/request.md
Labels: Design

#704 Always display sub-sub pages in the sidebar nav
  _includes/secondary-nav.html
  _sass/minima/_nav-list.scss
  _sass/minima/_site-header.scss
Labels: Dev, Design

#708 Added home page banner theme by Susrita
  _compress_images_cache.yml
  assets/images/home/banner/ongoing-development-mobile.png
  assets/images/home/banner/ongoing-development-mobile@2x.png
  assets/images/home/banner/ongoing-development.png
  assets/images/home/banner/ongoing-development@2x.png
  js/themes.js
Labels: Design

#709 Added formatting tips for very small amounts
  guide/payments/units-and-symbols.md
Labels: Copy

#729 Add new `Resources` chapter
  _compress_images_cache.yml
  assets/images/guide/designing-products/design-resources/bitcoin-design-site.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-design-site@2x.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-icons.jpg
  assets/images/guide/designing-products/design-resources/bitcoin-icons@2x.jpg
  assets/images/guide/designing-products/design-resources/design-resources-preview.jpg
  assets/images/guide/designing-products/user-research/adoption.jpg
  assets/images/guide/designing-products/user-research/adoption@2x.jpg
  assets/images/guide/designing-products/user-research/global-audience.jpg
  assets/images/guide/designing-products/user-research/global-audience@2x.jpg
  assets/images/guide/designing-products/user-research/private.jpg
  assets/images/guide/designing-products/user-research/private@2x.jpg
  assets/images/guide/designing-products/user-research/public-ledger.jpg
  assets/images/guide/designing-products/user-research/public-ledger@2x.jpg
  assets/images/guide/designing-products/user-research/user-research.jpg
  assets/images/guide/designing-products/user-research/user-research@2x.jpg
  assets/images/guide/resources/design-files/art-meets-bitcoin.jpg
  assets/images/guide/resources/design-files/art-meets-bitcoin@2x.jpg
  assets/images/guide/resources/design-files/bitcoin-design-community-seal.jpg
  assets/images/guide/resources/design-files/bitcoin-design-community-seal@2x.jpg
  assets/images/guide/resources/design-files/bitcoin-design-community.zip
  assets/images/guide/resources/design-files/bitcoin-design-site.jpg
  assets/images/guide/resources/design-files/bitcoin-design-site@2x.jpg
  assets/images/guide/resources/design-files/bitcoin-hardware-illustrations.jpg
  assets/images/guide/resources/design-files/bitcoin-hardware-illustrations@2x.jpg
  assets/images/guide/resources/design-files/bitcoin-icons.jpg
  assets/images/guide/resources/design-files/bitcoin-icons@2x.jpg
  assets/images/guide/resources/design-files/bitcoin-ui-kit.jpg
  assets/images/guide/resources/design-files/bitcoin-ui-kit@2x.jpg
  assets/images/guide/resources/design-files/design-resources-preview.jpg
  assets/images/guide/resources/design-files/slide-template.jpg
  assets/images/guide/resources/design-files/slide-template@2x.jpg
  assets/images/guide/resources/design-research/user-research-resources-mobile.jpg
  assets/images/guide/resources/design-research/user-research-resources-mobile@2x.jpg
  assets/images/guide/resources/design-research/user-research-resources-preview.jpg
  assets/images/guide/resources/design-research/user-research-resources.jpg
  assets/images/guide/resources/design-research/user-research-resources@2x.jpg
  guide/case-studies/shared-account.md
  guide/contribute/contribute.md
  guide/contribute/formatting.md
  guide/designing-products/designing-products.md
  guide/designing-products/usage-life-cycle.md
  guide/designing-products/wallet-interoperability.md
  guide/onboarding/introduction.md
  guide/resources/design-files.md
  guide/resources/design-research.md
  guide/resources/introduction.md
Labels: Copy
