Repository BitcoinDesign/Guide, pull requests merged in 2022-02, with the labels that each got.

#634 Added more relevant link CTAs to the home page
  index.md
Labels: copy

#629 Modal Images
  _compress_images_cache.yml
  _includes/picture.html
  _sass/minima/_article.scss
  _sass/minima/_base.scss
  assets/images/guide/contribute/formatting/example-image-mobile-screen-modal.png
  assets/images/guide/contribute/formatting/example-image-mobile-screen-modal@2x.png
  assets/images/guide/contribute/formatting/example-optional-image-modal-mobile.png
  assets/images/guide/contribute/formatting/example-optional-image-modal-mobile@2x.png
  assets/images/guide/contribute/formatting/example-optional-image-modal.png
  assets/images/guide/contribute/formatting/example-optional-image-modal@2x.png
  assets/loading-spinner.svg
  guide/contribute/formatting.md
  js/scripts.js
Labels: enhancement, dev

#625 Restructured `Payments` chapter.
  guide/glossary/coin-selection.md
  guide/payments/introduction.md
  guide/payments/payment-request-formats.md
  guide/payments/privacy.md
  guide/payments/request.md
  guide/payments/send.md
  guide/payments/transactions.md
  guide/payments/units-and-symbols.md
Labels: enhancement, copy

#637 Modal image updates
  _compress_images_cache.yml
  _includes/picture.html
  _includes/svgs.html
  _sass/minima/_base.scss
  guide/contribute/formatting.md
  js/scripts.js
Labels: enhancement, dev

#636 Payment privacy page minor Lightning iteration
  guide/payments/privacy.md
Labels: payments, copy

#639 Fix for modal images in gallery view
  _sass/minima/_base.scss
  _sass/minima/article/_image-slide-gallery.scss
  guide/case-studies/cloud-backup.md
Labels: bug, dev

#662 New activity page
  _compress_images_cache.yml
  assets/images/guide/payments/activity/activity-header-mobile.png
  assets/images/guide/payments/activity/activity-header-mobile@2x.png
  assets/images/guide/payments/activity/activity-header.png
  assets/images/guide/payments/activity/activity-header@2x.png
  assets/images/guide/payments/activity/activity.png
  assets/images/guide/payments/activity/activity@2x.png
  assets/images/guide/payments/activity/annotated-activity.png
  assets/images/guide/payments/activity/annotated-activity@2x.png
  assets/images/guide/payments/activity/budgeting.png
  assets/images/guide/payments/activity/budgeting@2x.png
  assets/images/guide/payments/activity/grouped-micropayments.png
  assets/images/guide/payments/activity/grouped-micropayments@2x.png
  assets/images/guide/payments/activity/micropayments.png
  assets/images/guide/payments/activity/micropayments@2x.png
  assets/images/guide/payments/activity/non-payment-activity.png
  assets/images/guide/payments/activity/non-payment-activity@2x.png
  assets/images/guide/payments/activity/receive-transaction-expanded.png
  assets/images/guide/payments/activity/receive-transaction-expanded@2x.png
  assets/images/guide/payments/activity/receive-transaction-id-details.png
  assets/images/guide/payments/activity/receive-transaction-id-details@2x.png
  assets/images/guide/payments/activity/receive-transaction.png
  assets/images/guide/payments/activity/receive-transaction@2x.png
  assets/images/guide/payments/activity/search.png
  assets/images/guide/payments/activity/search@2x.png
  assets/images/guide/payments/activity/send-transaction-expanded.png
  assets/images/guide/payments/activity/send-transaction-expanded@2x.png
  assets/images/guide/payments/activity/send-transaction.png
  assets/images/guide/payments/activity/send-transaction@2x.png
  assets/images/guide/payments/activity/status-field.png
  assets/images/guide/payments/activity/status-field@2x.png
  assets/images/guide/payments/activity/tips.png
  assets/images/guide/payments/activity/tips@2x.png
  assets/images/guide/payments/activity/to-field.png
  assets/images/guide/payments/activity/to-field@2x.png
  guide/payments/activity.md
  guide/payments/privacy.md
  guide/payments/send.md
Labels: Payments, Copy, Design

#666 Follow-up tweaks to the activity page
  _compress_images_cache.yml
  assets/images/guide/payments/activity/activity-ids.png
  assets/images/guide/payments/activity/activity-ids@2x.png
  assets/images/guide/payments/activity/activity-preview.jpg
  assets/images/guide/payments/activity/activity.png
  assets/images/guide/payments/activity/activity@2x.png
  assets/images/guide/payments/activity/invoice.png
  assets/images/guide/payments/activity/invoice@2x.png
  assets/images/guide/payments/activity/semi-annotated-activity.png
  assets/images/guide/payments/activity/semi-annotated-activity@2x.png
  assets/images/guide/payments/activity/sending.png
  assets/images/guide/payments/activity/sending@2x.png
  guide/designing-products/common-user-flows.md
  guide/payments/activity.md
  guide/payments/introduction.md
Labels: Payments, Copy, Design

#670 Grammar fixes for tech primer
  guide/getting-started/technology-primer.md
Labels: Copy

#677 Remove redundant word
  guide/payments/send.md
Labels: Copy

#672 Added details on security steps as last step before sending payment
  _compress_images_cache.yml
  assets/images/guide/payments/send/enter-pin-before-payment.png
  assets/images/guide/payments/send/enter-pin-before-payment@2x.png
  guide/payments/send.md
Labels: Copy

#626 Added address reuse to `Glossary` > `Address` page
  guide/glossary/address.md
Labels: Documentation, Copy

#683 Recommend 12 over 24 word recovery phrases
  guide/designing-products/common-user-flows.md
  guide/designing-products/getting-to-know-your-users.md
  guide/designing-products/principles.md
  guide/getting-started/hardware.md
  guide/glossary/index.md
  guide/glossary/wallet.md
  guide/onboarding/cloud-backup.md
  guide/onboarding/first-use.md
  guide/onboarding/manual-backup.md
  guide/onboarding/protecting-a-wallet.md
  guide/onboarding/restoring-a-wallet.md
  guide/private-key-management/external-signer.md
Labels: Copy

#682 Minor readme revision
  README.md
Labels: Copy
