Repository BitcoinDesign/Guide, pull requests merged in 2022-07, with the labels that each got.

#827 Added content about guiding users towards using lightning
  _compress_images_cache.yml
  assets/images/guide/daily-spending-wallet/sending/onchain-warning.png
  assets/images/guide/daily-spending-wallet/sending/onchain-warning@2x.png
  assets/images/guide/daily-spending-wallet/sending/review-onchain-tx.png
  assets/images/guide/daily-spending-wallet/sending/review-onchain-tx@2x.png
  assets/images/guide/daily-spending-wallet/sending/scan-onchain-qr-code.png
  assets/images/guide/daily-spending-wallet/sending/scan-onchain-qr-code@2x.png
  guide/daily-spending-wallet/sending.md
Labels: Daily spending wallet

#832 Updated `Payment request format` page
  _compress_images_cache.yml
  assets/images/guide/how-it-works/payment-request-formats/adresses-mobile.jpg
  assets/images/guide/how-it-works/payment-request-formats/adresses-mobile@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/adresses.jpg
  assets/images/guide/how-it-works/payment-request-formats/adresses@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/amp.jpg
  assets/images/guide/how-it-works/payment-request-formats/amp@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/invoice.jpg
  assets/images/guide/how-it-works/payment-request-formats/invoice@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/lnurl-mobile.jpg
  assets/images/guide/how-it-works/payment-request-formats/lnurl-mobile@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/lnurl.jpg
  assets/images/guide/how-it-works/payment-request-formats/lnurl@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/node.jpg
  assets/images/guide/how-it-works/payment-request-formats/node@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/offer.jpg
  assets/images/guide/how-it-works/payment-request-formats/offer@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-code.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-code@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-request-formats-mobile.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-request-formats-mobile@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-request-formats-preview.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-request-formats.jpg
  assets/images/guide/how-it-works/payment-request-formats/payment-request-formats@2x.jpg
  assets/images/guide/how-it-works/payment-request-formats/unified.jpg
  assets/images/guide/how-it-works/payment-request-formats/unified@2x.jpg
  guide/how-it-works/payment-request-formats.md
Labels: Copy, How it works

#870 Minor readme update & broken link fixes
  README.md
  guide/glossary/index.md
  guide/how-it-works/payment-request-formats.md
Labels: Bug, Documentation

#871 Add bolt.fun and bitcoinqr.dev to the projects page
  _compress_images_cache.yml
  assets/images/contribute/bitcoinqr.png
  assets/images/contribute/bolt-fun.png
  projects.md
Labels: Documentation

#862 First use page revision
  _compress_images_cache.yml
  assets/images/guide/daily-spending-wallet/first-use/app-store-listing-full.png
  assets/images/guide/daily-spending-wallet/first-use/app-store-listing.png
  assets/images/guide/daily-spending-wallet/first-use/app-store-listing@2x.png
  assets/images/guide/daily-spending-wallet/first-use/cloud-backup-full.png
  assets/images/guide/daily-spending-wallet/first-use/cloud-backup.png
  assets/images/guide/daily-spending-wallet/first-use/cloud-backup@2x.png
  assets/images/guide/daily-spending-wallet/first-use/funding-address-full.png
  assets/images/guide/daily-spending-wallet/first-use/funding-address.png
  assets/images/guide/daily-spending-wallet/first-use/funding-address@2x.png
  assets/images/guide/daily-spending-wallet/first-use/funding-options-full.png
  assets/images/guide/daily-spending-wallet/first-use/funding-options.png
  assets/images/guide/daily-spending-wallet/first-use/funding-options@2x.png
  assets/images/guide/daily-spending-wallet/first-use/home-receiving-full.png
  assets/images/guide/daily-spending-wallet/first-use/home-receiving.png
  assets/images/guide/daily-spending-wallet/first-use/home-receiving@2x.png
  assets/images/guide/daily-spending-wallet/first-use/home-security-reminder-full.png
  assets/images/guide/daily-spending-wallet/first-use/home-security-reminder.png
  assets/images/guide/daily-spending-wallet/first-use/home-security-reminder@2x.png
  assets/images/guide/daily-spending-wallet/first-use/initial-receive-fees-full.png
  assets/images/guide/daily-spending-wallet/first-use/initial-receive-fees.png
  assets/images/guide/daily-spending-wallet/first-use/initial-receive-fees@2x.png
  assets/images/guide/daily-spending-wallet/first-use/initial-receive-full.png
  assets/images/guide/daily-spending-wallet/first-use/initial-receive.png
  assets/images/guide/daily-spending-wallet/first-use/initial-receive@2x.png
  assets/images/guide/daily-spending-wallet/first-use/onboarding-welcome-screen-full.png
  assets/images/guide/daily-spending-wallet/first-use/onboarding-welcome-screen.png
  assets/images/guide/daily-spending-wallet/first-use/onboarding-welcome-screen@2x.png
  assets/images/guide/daily-spending-wallet/first-use/product-intro-1.png
  assets/images/guide/daily-spending-wallet/first-use/product-intro-1@2x.png
  assets/images/guide/daily-spending-wallet/first-use/product-intro-2.png
  assets/images/guide/daily-spending-wallet/first-use/product-intro-2@2x.png
  assets/images/guide/daily-spending-wallet/first-use/product-intro-3.png
  assets/images/guide/daily-spending-wallet/first-use/product-intro-3@2x.png
  assets/images/guide/daily-spending-wallet/first-use/responsibility-disclaimer-full.png
  assets/images/guide/daily-spending-wallet/first-use/responsibility-disclaimer.png
  assets/images/guide/daily-spending-wallet/first-use/responsibility-disclaimer@2x.png
  assets/images/guide/daily-spending-wallet/first-use/security-reminder-full.png
  assets/images/guide/daily-spending-wallet/first-use/security-reminder.png
  assets/images/guide/daily-spending-wallet/first-use/security-reminder@2x.png
  assets/images/guide/daily-spending-wallet/first-use/security-setup-full.png
  assets/images/guide/daily-spending-wallet/first-use/security-setup.png
  assets/images/guide/daily-spending-wallet/first-use/security-setup@2x.png
  guide/daily-spending-wallet/first-use.md
  guide/daily-spending-wallet/landing-page.md
Labels: Copy, Design, Daily spending wallet

#877 Adds an include for video links with small thumbnails
  _compress_images_cache.yml
  _includes/video.html
  _includes/videos.html
  _sass/minima/_article.scss
  assets/images/guide/contribute/formatting/supporting-open-design-in-bitcoin.jpg
  assets/images/guide/contribute/formatting/supporting-open-design-in-bitcoin@2x.jpg
  assets/images/guide/contribute/formatting/user-research-call-1-user-personas.jpg
  assets/images/guide/contribute/formatting/user-research-call-1-user-personas@2x.jpg
  guide/contribute/formatting.md
Labels: Documentation, Dev

#879 Splits formatting page in two pages
  _compress_images_cache.yml
  assets/animations/contribute/formatting/bitcoin-design-seal.png
  assets/animations/contribute/formatting/media/bitcoin-design-seal-miami-edition.json
  assets/animations/contribute/formatting/media/bitcoin-design-seal-miami-edition.png
  assets/animations/contribute/formatting/media/bitcoin-design-seal-miami-edition@2x.png
  assets/animations/contribute/formatting/media/bitcoin-design-seal.json
  assets/animations/contribute/formatting/media/bitcoin-design-seal.png
  assets/animations/contribute/formatting/media/bitcoin-design-seal@2x.png
  assets/images/guide/contribute/formatting/media/example-image-mobile-screen-modal.png
  assets/images/guide/contribute/formatting/media/example-image-mobile-screen-modal@2x.png
  assets/images/guide/contribute/formatting/media/example-image-mobile-screen.png
  assets/images/guide/contribute/formatting/media/example-image-mobile-screen@2x.png
  assets/images/guide/contribute/formatting/media/example-image-square.jpg
  assets/images/guide/contribute/formatting/media/example-image-square@2x.jpg
  assets/images/guide/contribute/formatting/media/example-image-wide-desktop.jpg
  assets/images/guide/contribute/formatting/media/example-image-wide-desktop@2x.jpg
  assets/images/guide/contribute/formatting/media/example-image-wide-mobile.jpg
  assets/images/guide/contribute/formatting/media/example-image-wide-mobile@2x.jpg
  assets/images/guide/contribute/formatting/media/example-optional-image-modal-mobile.png
  assets/images/guide/contribute/formatting/media/example-optional-image-modal-mobile@2x.png
  assets/images/guide/contribute/formatting/media/example-optional-image-modal.png
  assets/images/guide/contribute/formatting/media/example-optional-image-modal@2x.png
  assets/images/guide/contribute/formatting/media/formatting-media-mobile.jpg
  assets/images/guide/contribute/formatting/media/formatting-media-mobile@2x.jpg
  assets/images/guide/contribute/formatting/media/formatting-media-preview.jpg
  assets/images/guide/contribute/formatting/media/formatting-media.jpg
  assets/images/guide/contribute/formatting/media/formatting-media@2x.jpg
  assets/images/guide/contribute/formatting/media/prototype-example-mobile.png
  assets/images/guide/contribute/formatting/media/prototype-example-mobile@2x.png
  assets/images/guide/contribute/formatting/media/prototype-example.png
  assets/images/guide/contribute/formatting/media/prototype-example@2x.png
  assets/images/guide/contribute/formatting/media/supporting-open-design-in-bitcoin.jpg
  assets/images/guide/contribute/formatting/media/supporting-open-design-in-bitcoin@2x.jpg
  assets/images/guide/contribute/formatting/media/user-research-call-1-user-personas.jpg
  assets/images/guide/contribute/formatting/media/user-research-call-1-user-personas@2x.jpg
  guide/contribute/formatting.md
  guide/contribute/formatting/index.md
  guide/contribute/formatting/media.md
Labels: Documentation
