Repository BitcoinDesign/Guide, pull requests merged in 2023-11, with the labels that each got.

#1027 Add code resources page
  guide/daily-spending-wallet/landing-page.md
  guide/resources/code-resources.md
  guide/resources/design-challenges.md
  guide/resources/introduction.md
Labels: Enhancement

#1046 Minor copy tweaks to visual language & user research
  guide/designing-products/user-research.md
  guide/getting-started/visual-language.md
Labels: Copy

#1049 Update _compress_images_cache.yml
  _compress_images_cache.yml
Labels: Dev

#1051 Add links to the Bitcoin Design Foundation
  _compress_images_cache.yml
  assets/images/contribute/foundation.png
  contribute.md
  projects.md
Labels: Documentation

#1050 Updated header image for the manual backup page
  _compress_images_cache.yml
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/backing-up-a-wallet-manual-mobile.png
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/backing-up-a-wallet-manual-mobile@2x.png
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/backing-up-a-wallet-manual-preview.png
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/backing-up-a-wallet-manual.png
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/backing-up-a-wallet-manual@2x.png
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/manual-backup-mobile.jpg
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/manual-backup-mobile@2x.jpg
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/manual-backup-preview.jpg
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/manual-backup.jpg
  assets/images/guide/daily-spending-wallet/backup-and-recovery/manual-backup/manual-backup@2x.jpg
  guide/daily-spending-wallet/backup-and-recovery/manual-backup.md
Labels: Design

#1052 Add an example to the descriptors glossary entry
  _compress_images_cache.yml
  assets/images/guide/glossary/descriptor-example.png
  assets/images/guide/glossary/descriptor-example@2x.png
  guide/glossary/index.md
Labels: Copy
